### ISSUE TITLE
[4.x]: Changing a channel into a structure breaks entry list

### ISSUE THREAD

**Issue by Nellyaa** [craftcms/cms#11000]
### Description

When you change a channel section into a structure section that already has entries and go to Entries -> <that section>, the little arrows to drag the entries up and down aren't appearing.
You can choose a parent within the edit entry page, but it won't show up correctly neither in the modal field where you pick it (arrows to open a dropdown are there, but contents are empty) nor in the entry list page.

### Steps to reproduce

1. Create channel section
2. Fill structure with some entries
3. Change section into a structure
4. Revisit that entry section
5. See no arrows are appearing, you can't drag anything or make anything child/parent of each other

### Expected behavior

Arrows appear and you can drag the entries around as expected.

### Actual behavior

![#](https://user-images.githubusercontent.com/38379317/164888381-04905516-0b12-4b1f-977d-76d54d02bf4d.jpg)
![Unbenannt-1](https://user-images.githubusercontent.com/38379317/164888423-95ceb970-818d-43b8-8d8e-99221718bd93.jpg)

### Craft CMS version

4.0.0-beta.4

### PHP version

8.1.3

### Operating system and version

Linux 5.10.16.3-microsoft-standard-WSL2

### Database type and version

MySQL 10.7.3

**Comment by brandonkelly** [comment]
They will appear if you change the sort option to “Structure”. (However there is a separate issue where the selected sort option isn’t sticking, which is fixed for the next release via 17a6e6eaf702c0bfa3c435421065d0476d434779).

**Comment by Nellyaa** [comment]
Thanks, but the problem of the second screenshot still exists. If you go to an entry, choose parent and the modal appears. The 'support' entry has children, but they don't show up when you click on the arrow.

**Comment by Nellyaa** [comment]
Quick and dirty video to show the problem

https://user-images.githubusercontent.com/38379317/164889292-f19615ec-376c-41cc-ab9d-fbb6981ec2d8.mp4

**Comment by brandonkelly** [comment]
Ah ok, thanks. Will look into that tomorrow.

**Comment by brandonkelly** [comment]
@Nellyaa I’m not able to reproduce that. Are you seeing the same thing happen on the Entries index page?

**Comment by Nellyaa** [comment]
@brandonkelly The arrows work fine on the entry index page for me - problem just occured in the modal view. 
However, after trying again today it started working again. I can't reproduce it anymore. Sorry.

**Comment by brandonkelly** [comment]
Weird! The only way I can reproduce is if I’m editing an entry that is the only child of its parent. So the parent shows the arrow because it technically has a child, but it won’t show it because the child is the entry being edited.

**Comment by brandonkelly** [comment]
Will go ahead and close for now, but let me know if it crops back up again.
