### ISSUE TITLE
[4.x]: Asset thumbnails and image inside the editor are not updated/refreshed when using the image editor to make a change, such as flipping the image.

### ISSUE THREAD

**Issue by terryupton** [craftcms/cms#12603]
### Description
When you make a change to an asset in the image edit, these changes are not reflected inside the CMS and the original thumbnails and image inside the editor panel are cached.  

### Steps to reproduce
1. Open an image inside the asset panel from the thumnails.
2. Click to edit the image and open the image edit.
3. Make a simple change, for example flip the image.

Here is a video to illustrate the issue and the process. 

https://user-images.githubusercontent.com/5698596/216013090-ed0600ce-ff65-4c73-b25c-e58835ccccc7.mov

### Expected behavior
After editing the image, I would expect the following to update and show the image changes:
1. The image inside the editor
2. The thumbnail image in the slide out panel.
3. The image in the asset listing panel.

### Actual behavior
None of the images inside Craft are updating.
If I load the thumbnail in a browser and refresh the image, I see this change in the CMS, but ONLY inside the slide out panel.

When testing this locally, I see the same issues. However, locally I do see the image in the  slide out panel update immediately. This is could perhaps be down to expires headers. However, it would be nice to resolve this if they are present and set.

### Craft CMS version

Craft Pro 4.3.6.1

### PHP version

8.1.14

### Operating system and version

Linux 5.15.0-56-generic

### Database type and version

MySQL 8.0.32

### Image driver and version

magick 3.7.0 (ImageMagick 6.9.11-60)

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Thanks for reporting that! The issue is that asset thumbnails weren’t getting versioned unless the `revAssetUrls` config setting was enabled, so your browser would continue loading the cached version. I’ve fixed this for the next release - going forward all CP thumbnails will be versioned regardless of the config setting.

**Comment by brandonkelly** [comment]
Craft 4.3.7 has been released with that fix.

**Comment by terryupton** [comment]
Hey @brandonkelly - thanks for this. 
However, I am still seeing the same issue on the image that appears on the image editor.
the thumbnails and everything now updates, but not the image when you go back into the image to edit it after making a change (rotation etc).

Thanks.

**Comment by brandonkelly** [comment]
@terryupton Doh, thanks for pointing that out. That’s been fixed for the next release as well.

**Comment by brandonkelly** [comment]
4.3.8.1 is out with that fix. Note that if you updated to 4.3.8 already, via the control panel, you will be affected by [this bug](https://github.com/craftcms/cms/issues/12647), which was also fixed in 4.3.8.1. If so you will need to run `composer update` to fix.
