### ISSUE TITLE
[4.x]: Error when running -  php craft entrify/global-set

### ISSUE THREAD

**Issue by DenyEs** [craftcms/cms#13156]
### Description
Running  php craft entrify/global-set exampleSet returns an error when saving the entry type.

### Steps to reproduce

1. Try to entrify global set

### Expected behavior
Creates a new section with entry type and migrates the content over.

### Actual behavior
Throws the following error.

```
Error: craft\models\FieldLayout::createFromConfig(): Argument #1 ($config) must be of type array, null given, called in /Users/deny/Documents/sites/website/vendor/craftcms/cms/src/console/controllers/SectionsController.php on line 232
Exception 'TypeError' with message 'craft\models\FieldLayout::createFromConfig(): Argument #1 ($config) must be of type array, null given, called in /Users/deny/Documents/sites/website/vendor/craftcms/cms/src/console/controllers/SectionsController.php on line 232'

in /Users/deny/Documents/sites/website/vendor/craftcms/cms/src/models/FieldLayout.php:171

Stack trace:
#0 /Users/deny/Documents/sites/website/vendor/craftcms/cms/src/console/controllers/SectionsController.php(232): craft\models\FieldLayout::createFromConfig(NULL)
#1 /Users/deny/Documents/sites/website/vendor/craftcms/cms/src/console/Controller.php(452): craft\console\controllers\SectionsController->craft\console\controllers\{closure}()
#2 /Users/deny/Documents/sites/website/vendor/craftcms/cms/src/console/controllers/SectionsController.php(243): craft\console\Controller->do('Saving the entr...', Object(Closure))
#3 [internal function]: craft\console\controllers\SectionsController->actionCreate()
#4 /Users/deny/Documents/sites/website/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#5 /Users/deny/Documents/sites/website/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#6 /Users/deny/Documents/sites/website/vendor/yiisoft/yii2/console/Controller.php(180): yii\base\Controller->runAction('create', Array)
#7 /Users/deny/Documents/sites/website/vendor/craftcms/cms/src/console/ControllerTrait.php(87): yii\console\Controller->runAction('create', Array)
#8 /Users/deny/Documents/sites/website/vendor/craftcms/cms/src/console/Controller.php(217): craft\console\Controller->traitRunAction('create', Array)
#9 /Users/deny/Documents/sites/website/vendor/yiisoft/yii2/base/Module.php(552): craft\console\Controller->runAction('create', Array)
#10 /Users/deny/Documents/sites/website/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('sections/create', Array)
#11 /Users/deny/Documents/sites/website/vendor/craftcms/cms/src/console/Application.php(90): yii\console\Application->runAction('sections/create', Array)
#12 /Users/deny/Documents/sites/website/vendor/yiisoft/yii2/base/Controller.php(212): craft\console\Application->runAction('sections/create', Array)
#13 /Users/deny/Documents/sites/website/vendor/craftcms/cms/src/console/Controller.php(208): yii\base\Controller->run('sections/create', Array)
#14 /Users/deny/Documents/sites/website/vendor/craftcms/cms/src/console/controllers/EntrifyController.php(460): craft\console\Controller->run('sections/create', Array)
#15 [internal function]: craft\console\controllers\EntrifyController->actionGlobalSet(Object(craft\elements\GlobalSet))
#16 /Users/deny/Documents/sites/website/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#17 /Users/deny/Documents/sites/website/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#18 /Users/deny/Documents/sites/website/vendor/yiisoft/yii2/console/Controller.php(180): yii\base\Controller->runAction('global-set', Array)
#19 /Users/deny/Documents/sites/website/vendor/craftcms/cms/src/console/ControllerTrait.php(87): yii\console\Controller->runAction('global-set', Array)
#20 /Users/deny/Documents/sites/website/vendor/craftcms/cms/src/console/Controller.php(217): craft\console\Controller->traitRunAction('global-set', Array)
#21 /Users/deny/Documents/sites/website/vendor/yiisoft/yii2/base/Module.php(552): craft\console\Controller->runAction('global-set', Array)
#22 /Users/deny/Documents/sites/website/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('entrify/global-...', Array)
#23 /Users/deny/Documents/sites/website/vendor/craftcms/cms/src/console/Application.php(90): yii\console\Application->runAction('entrify/global-...', Array)
#24 /Users/deny/Documents/sites/website/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('entrify/global-...', Array)
#25 /Users/deny/Documents/sites/website/vendor/craftcms/cms/src/console/Application.php(121): yii\console\Application->handleRequest(Object(craft\console\Request))
#26 /Users/deny/Documents/sites/website/vendor/yiisoft/yii2/base/Application.php(384): craft\console\Application->handleRequest(Object(craft\console\Request))
#27 /Users/deny/Documents/sites/website/craft(13): yii\base\Application->run()
#28 {main}
```

### Craft CMS version

4.4.9

### PHP version

8.1.11

### Operating system and version

macOS Ventura 13.3

### Database type and version

MySQL 8.0.30

### Installed plugins and versions

Amazon S3 	2.0.3
Button Box 	4.2.0
Cookies 	4.0.0
CP Field Inspect 	1.4.4
Default Dashboard 	2.0.0
Dumper 	3.0.1
Embedded Assets 	3.1.5
Facebook Conversion 	v1.2.2
Freeform 	4.0.23
GDPR Cookie Consent 	4.0.4
Imager X 	4.1.12
Linkit 	4.0.4.1
LJ Dynamic Fields 	4.0.3
Maps 	v4.0.3
MobileDetect 	2.0.0
Obfuscator 	1.1.1
Position Fieldtype 	4.0.0
Redactor 	3.0.4
Retour 	4.1.12
Section Field 	2.0.0
SEOmatic 	4.0.24
Sherlock 	4.3.0
Sprig 	2.6.2
Super Table 	3.0.8.1
Table Maker 	4.0.6
Template Select 	3.0.0
Wordsmith 	4.2.0

**Comment by DenyEs** [comment]
Issue has been on our side - Global set was empty...

**Comment by brandonkelly** [comment]
Fixed for the next release nonetheless. Thanks for reporting!

**Comment by brandonkelly** [comment]
Craft 4.8.10 is out now with that fix.

**Comment by stephenmatthews** [comment]
Still getting the same issue with an empty global set when on Craft v 5
