### ISSUE TITLE
[5.x]: Incorrect CP console request URLs

### ISSUE THREAD

**Issue by bencroker** [craftcms/cms#15374]
### What happened?

The commit https://github.com/craftcms/cms/commit/8e69802d89556d4432002fed3754404a4e8e0252 addressed constructing URLs for console requests if the `@web` alias wasn’t explicitly defined. Should a similar change not also be applied to CP console requests to ensure that CP URLs are output as absolute URLs?

### Steps to reproduce

1. In a custom module, create a console command that outputs an entry’s CP edit URL.
```php
die(\craft\helpers\UrlHelper::cpUrl());
```

### Expected behavior

The output should be `https://projectpath.ddev.site/admin`.

### Actual behavior

The output is `/admin`.

_Tested in Craft 5 but this likely affects Craft 4 as well._

### Craft CMS version

5.2.7

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
We’ll discuss!

**Comment by brandonkelly** [comment]
Decided to make this change for 4.11 and 5.3 (#15403). It’s not as urgently needed as the `actionUrl()` change was, thanks to the [`baseCpUrl`](https://craftcms.com/docs/5.x/reference/config/general.html#basecpurl) config setting.

**Comment by bencroker** [comment]
Lovely, thanks!

**Comment by white-lukas** [comment]
@brandonkelly we are now getting a typeError on the `fallbackBaseUrl()`
```
craft\helpers\UrlHelper::fallbackBaseUrl(): Argument #1 ($request) must be of type ?craft\web\Request, craft\console\Request given, 
called in /var/www/html/vendor/craftcms/cms/src/helpers/UrlHelper.php on line 646
```

**Comment by brandonkelly** [comment]
@white-lukas Thanks for letting me know. Fixed via a94c6cd2e39f88e62b8e60b80ea0a846f181b533.

**Comment by sajjanstha** [comment]
@brandonkelly Did you push the fix for above typeError on the fallbackBaseUrl() for craft 4? I am still facing the below error when I upgraded my craft cms to 4.11.0.2.
`Exception 'TypeError' with message 'craft\helpers\UrlHelper::fallbackBaseUrl(): Argument #1 ($request) must be of type ?craft\web\Request, craft\console\Request given, called in /var/www/html/app/vendor/craftcms/cms/src/helpers/UrlHelper.php on line 655'`

**Comment by brandonkelly** [comment]
@sajjanstha Doh, forgot to apply the fix to Craft 4. Just tagged 4.11.1 with the same fix.
