### ISSUE TITLE
[Craft3 Beta] Postgres index error on `text` on save

### ISSUE THREAD

**Issue by rkingon** [craftcms/cms#1768]
### Description
Getting the following error when trying to save long text using Postgres in a RichText field

> SQLSTATE[54000]: Program limit exceeded: 7 ERROR:  index row size 2880 exceeds maximum 2712 for index &quot;searchindex_keywords_idx&quot;

### Steps to reproduce

1. Create richtext field
2. Put a load of lorem ipsum in it
3. Don't repeat the same paragraph, use different ones

### Additional info

- Craft version: 3.0.0-beta.10
- PHP version: 7.1.4
- Database driver & version: Postgres 9.6.2
- Plugins & versions: None

**Comment by rkingon** [comment]
that was fast! thanks @takobell =]

**Comment by rkingon** [comment]
Hey brad, I just pulled down `dev-develop` which put me at commit 57353bb and tested this... I'm still getting the error =/

> SQLSTATE[54000]: Program limit exceeded: 7 ERROR:  index row size 2760 exceeds maximum 2712 for index "searchindex_keywords_idx"
> HINT:  Values larger than 1/3 of a buffer page cannot be indexed.
> Consider a function index of an MD5 hash of the value, or use full text indexing.

**Comment by takobell** [comment]
@rkingon weird... can you share the text you're testing with in a gist?

**Comment by rkingon** [comment]
I literally just used the text from:

http://www.lipsum.com/

`The standard Lorem Ipsum passage, used since the 1500s` -> `1914 translation by H. Rackham` paragraphs

**Comment by takobell** [comment]
Hrm... that's what I used, too.  Will test again.

**Comment by rkingon** [comment]
just to be thorough, I double checked the code in my `vendor/craftcms/cms` and I am indeed on the tip of the develop branch.

if you want I can deploy the latest and give you cp access too

**Comment by takobell** [comment]
Really resolved in https://github.com/craftcms/cms/commit/5dd36908b678f38991e5b3b49008b7a7de249fdd

**Comment by spleenboy** [comment]
We're still seeing this issue with multi-byte character strings (Mandarin Chinese in our case). `mb_strlen` is reporting the character count rather than the actual byte size, so it's not truncating enough to fit within the 2172 limit. Looks like [`strlen`](https://secure.php.net/manual/en/function.strlen.php#118484) may be needed to get the right size.

**Comment by brandonkelly** [comment]
@spleenboy yep you’re right. Just changed that back to `strlen()`
