### ISSUE TITLE
Relative Craft.actionUrl breaks ajax requests for sites not on the root domain

### ISSUE THREAD

**Issue by alexmarchant** [craftcms/cms#2487]
### Description

Either RC11 or RC12 broke the actionUrl and thus all ajax queries (can't login!) for my site that does not sit on the root domain (i.e. the siteUrl is https://staging.mastinlabs.com/photoism/ not https://staging.mastinlabs.com/). 

On my production server, we're running RC10.1 and Craft.actionUrl is `https://www.mastinlabs.com/photoism/index.php?p=admin/actions` on my staging server we're running RC12 and Craft.actionUrl is a relative url `/index.php?p=admin/actions`.

I saw there were some updates to the UrlHelper class, is that where this change came from?

### Steps to reproduce

1. Set up a craft server that doesn't sit on the root domain.
2. See all ajax queries fail.

### Additional info

- Craft version: Craft Pro 3.0.0-RC12
- PHP version: 7.2.1
- Database driver & version: PostgreSQL 10.1
- Plugins & versions:

Element API	2.5.2
Redactor	1.0.1
Amazon S3	1.0.8

**Comment by brandonkelly** [comment]
This was fixed in 60972fce0ae1fc230744972fd77283101e6c55e9. To update to that ahead of RC13, change your `craftcms/cms` version requirement in composer.json to `"dev-develop as 3.0.0-RC99"`, and then run `composer update`.

**Comment by alexmarchant** [comment]
Ok i did that and it did add the host back, but it is not taking into account that the site root and domain root are not the same:

![image](https://user-images.githubusercontent.com/953244/36622403-fac7e832-18ca-11e8-8134-1c962301bd2e.png)

**Comment by alexmarchant** [comment]
its still missing the `photoism`, is there something i can add to config to make this work, or is this a bug?

**Comment by alexmarchant** [comment]
Overrode the `actionUrl` twig extension and prepending the `siteUrl` to the RC12 relative `actionUrl` has me back in action for now. But `UrlHelper` should likely use siteUrl instead of the hostname from the request to build this, although i'm sure there is more complexity there that i don't understand.

**Comment by brandonkelly** [comment]
The URL is generated from [yii\web\Request::getScriptUrl()](http://www.yiiframework.com/doc-2.0/yii-web-request.html#getScriptUrl()-detail). If `/photoism/` is not showing up in the URL, then it‘s because the request is going through `/index.php`, not `/photoism/index.php` – or at least Yii thinks it is.

If you’re pretty sure it’s going through `/photoism/index.php`, try adding `die('test');` to the top of it, and see if it works. If it does, [here’s the source code](https://github.com/yiisoft/yii2/blob/master/framework/web/Request.php#L798) for `getScriptUrl()` – you can see how it’s trying to determine it, and figure out why it’s failing.

**Comment by alexmarchant** [comment]
Ah i see the issue. My index.php is at the root of the /web/ directory. So it is picking up the script url correctly.

But... we have a complex setup that is throwing it off. We have a wordpress server serving http://www.mastinlabs.com and i have Nginx proxying all requests to http://www.mastinlabs.com/photoism/ to our Craft server. So my index.php's url is actually at /photoism/index.php even though the script is at /index.php.

I'm not sure what changed since 10.1 but never had an issue before, maybe a yii update, or just started using the getScriptUrl function?

What do you think the best answer is here, is this a use case that should be covered by Craft's UrlHelper, or should i adjust my proxy and index.php location to align with the actual siteUrl?

If i should adjust my proxy and index.php location, i'd appreciate any insight you have into the proper way to do that.

**Comment by alexmarchant** [comment]
Would it be as simple as making a `photoism` folder inside the `web` directory and moving the `index.php` inside there and somehow letting craft know the new location?

**Comment by brandonkelly** [comment]
What changed is that in RT11, Craft no longer requires that each site’s base URL has their own directories with their own index.php files – Craft now analyzes the requested URL and is smart enough to determine which parts of the URL should be considered the “base”, vs. the requested URI.

A side effect of that is, Craft can no longer safely assume that the `index.php` file lives directly within the base URL, and so it has to start calling `getScriptUrl()` to figure that out (d5dd6b57). Which in this case sounds like a bug fix to me – previously Craft would  have assumed that the `index.php` URL is `/photoism/index.php`, which is incorrect, even if you were able to make it work from your server config.

> Would it be as simple as making a `photoism` folder inside the `web` directory and moving the `index.php` inside there and somehow letting craft know the new location?

Yep that is the right solution. You’ll basically just need to tell nginx to point all `/photoism/*` traffic to `/photoism/index.php`, and then make sure that your `CRAFT_BASE_PATH` constant is correct in that `index.php` file.

**Comment by alexmarchant** [comment]
OK, just got back from a long trip, yes this solution worked, moved the index.php and told nginx about it... thank you.

**Comment by brandonkelly** [comment]
Great! 👍
