### ISSUE TITLE
Issue adding rows and collumns in tables

### ISSUE THREAD

**Issue by ljclark** [craftcms/cms#2654]
### Description

Just upgraded to RC17 and the console is throwing an error when you try add a row or collum for a table field. - see attachment. 

<img width="509" alt="screen shot 2018-03-28 at 20 15 07" src="https://user-images.githubusercontent.com/8060816/38051607-b6f2ceb8-32c6-11e8-93c9-5c8b45fd46e0.png">

### Additional info

- Craft version: Craft Pro 3.0.0-RC17
- PHP version: 7.1.15
- Database driver & version: MySQL 5.5.59
- Browser: Firefox Quantum 59.0.1

**Plugins & versions:**

- Architect | 2.2.6
- Contact Form | 2.1.1
- CP Field Inspect | 1.0.4
- Default Tab | 1.2.2
- Environment Label | 3.1.3
- Expanded Singles | 1.0.3
- Minify | 1.2.8
- Redactor | 1.0.1
- SimpleMap | 3.3.3
- Splash | 3.0.2

**Comment by Radabaugh** [comment]
Thanks @ljclark, should be working now!

**Comment by ljclark** [comment]
Hey - still getting the same error on my site - do I need to do anything get this or is it coming in the next release? 

Cheers 
Lewis

**Comment by brandonkelly** [comment]
We just released Craft 3 RC17.1 with a fix for this.
