### ISSUE TITLE
'New Entry' dropdown not showing

### ISSUE THREAD

**Issue by jamiewade** [craftcms/cms#2961]
### Description

I suspect this is related to the issue I posted [here](https://github.com/craftcms/cms/issues/2942).

### Additional info

- Browser: Google Chrome 67.0.3396.62
- Craft version: 3.0.10
- PHP version: 7.1.4

![bug](https://user-images.githubusercontent.com/6672331/41041936-5333c108-6998-11e8-914a-d74b24529703.gif)

**Comment by brandonkelly** [comment]
Check your browser’s JavaScript console – are you getting any JS errors on the page?

**Comment by jamiewade** [comment]
Hey @brandonkelly, nope, no console errors at all. But thanks @andris-sevcenko for fixing!

**Comment by andris-sevcenko** [comment]
@jamiewade probably because we haven't released 3.0.10.2 yet :)

As a quick workaround, you can add another site to your install and the menu should work then until we release the next version.

**Comment by jamiewade** [comment]
@andris-sevcenko Apologies! It's not the end of the world, happy to wait for 3.0.10.2. Thanks Andris.

**Comment by brandonkelly** [comment]
@jamiewade We just released 3.0.10.2 with the fix.

**Comment by jamiewade** [comment]
@brandonkelly Unfortunately the issue still persists with 3.0.10.2. We've tested on a small, workbench Craft 3 installation we have that doesn't have any plugins, and it's the same story there 😞 

Also tested in:

- Firefox 60.0.2
- Edge 42.17134.1.0

**Comment by jamiewade** [comment]
@brandonkelly Following on from this, I tried Andris' suggestion of adding a new site, and the dropdown does now show. Once I then delete that new site, the dropdown goes back to not working.

**Comment by andris-sevcenko** [comment]
Just tested with a fresh install of 3.0.10.2 and everything is working. Have you tried clearing your cache? If that doesn't help, can you try emptying the `web/cpresources` folder?

**Comment by jamiewade** [comment]
Yeah as mentioned above I have been on top of doing these steps, I ran the same processes when I upgraded from `3.0.10.1` -> `3.0.10.2` as well.

Unfortunately it doesn't make any difference for either of our sites.

**Comment by brandonkelly** [comment]
Turns out the original fix only worked for PostgreSQL installs. Just released 3.0.10.3 with a fix for MySQL installs.
