### ISSUE TITLE
Duplicate entries in overview when saving field layout

### ISSUE THREAD

**Issue by stenvdb** [craftcms/cms#3525]
### Description
I see the same entry multiple times in my entries overview screen in the control panel.

### Steps to reproduce

1. Save a new entry in a channel
2. Update the channel's field layout
3. Return to the entries overview screen, I see the same entry appear 4 times (it increases each time by 4 when I save the field layout editor). They all have the same ID.

### Additional info

- Craft version: 3.1.0-beta.4
- PHP version: 7.1.12
- Database driver & version: MySQL 5.6.38
- Plugins & versions: I have disabled all plugins except Redactor

**Comment by stenvdb** [comment]
I noticed it only happend on my structure section. "Resolved" it by deleting the section, adding it again but as a channel.

**Comment by andris-sevcenko** [comment]
This was probably fixed with f1bdc9b08b8cb47597dc65be031bd94acf4fa409 and I'm not able to reproduce this.

When the next beta comes out (soon), can you try to reproduce this again?

**Comment by brandonkelly** [comment]
If there’s any chance you can test _before_ the next update goes out, we’d appreciate that as well! You can do that by updating your `craftcms/cms` requirement in composer.json:

```json
"require": {
    "craftcms/cms": "3.1.x-dev as 3.1.0-beta.4",
    "...": "..."
}
```

Then run `composer update`.

**Comment by stenvdb** [comment]
Hi @brandonkelly @andris-sevcenko I tested it and it's fixed when I add new sections. That section where I encountered the error still has this issue. But I will remove it and will add it again. I assume there went something wrong with the creation of the UID if I read https://github.com/craftcms/cms/commit/f1bdc9b08b8cb47597dc65be031bd94acf4fa409 commit. Good to see its fixed when adding new sections 👍 Thanks for the quick fix

**Comment by andris-sevcenko** [comment]
@stenvdb that would be great. If you could throw in some FTP creds as well, that'd be *fantastic*!

**Comment by stenvdb** [comment]
Where would you like me to mail the credentials to?

**Comment by andris-sevcenko** [comment]
Let's go with support@craftcms.com.

**Comment by thisisjamessmith** [comment]
Hm, this is still an issue for me after upgrading to beta-5.1? Following the same path as the first post in this thread.

**Comment by andris-sevcenko** [comment]
@thisisjamessmith there were two separate issues and the implemented fixes have not yet been a part of a release.

**Comment by thisisjamessmith** [comment]
DOH! sorry completely missed that fact. Have manually applied your fix now. As mentioned already above it's working now for adding new sections, though old sections still have the problem. I'll delete and recreate them manually unless you can think of an easier fix.

**Comment by thisisjamessmith** [comment]
Actually it seems I can fix older sections by deleting all the entries and then restoring them from the trash.

**Comment by andris-sevcenko** [comment]
Yeah, well, you also had to run the migration in https://github.com/craftcms/cms/commit/41275e10bcaf08c9eb67641b4cf1519788c8d38e :)
