### ISSUE TITLE
Project Config sync sometimes throws error when "allowAdminChanges" is set to "false"

### ISSUE THREAD

**Issue by jsunsawyer** [craftcms/cms#3823]
### Description
Testing out my first project config setup.

Adding a generic plain text field works, and the project config sync is successful.

Removing this field and re-deploying my project config returns the following error:

```{"error":"Changes to the project config are not possible while in read-only mode."}```

To resolve this, I have to update `'allowAdminChanges' => false` to `true`.

### Steps to reproduce

1. Add a plain text field using project config with `allowAdminChanges` set to `false`.
2. Deploy changes to another environment.
3. Navigate to CP to sync changes.
4. Remove the plain text field that you added.
5. Deploy changes again.
6. Attempt to sync – get error.

### Additional info

- Craft version: 3.1.8
- PHP version: 7.1.26

**Comment by brandonkelly** [comment]
Fixed that for the next release. Thanks for reporting1

**Comment by gilleard** [comment]
I think this may still be an issue, potentially after the later change in this commit as part of 3.1.11:

https://github.com/craftcms/cms/commit/8070026ea64a9e9d6757fd33566916e0b5b82b58

When the config's sync'd the AFTER_DELETE_FIELD event triggers several services' pruneDeletedField method, which passes the new/current comparison but then attempt to update the dateModified value.

**Comment by brandonkelly** [comment]
OK this should definitely be fixed now. @gilleard if you’re able to verify I’d appreciate it!

You can test by changing your `craftcms/cms` requirement in `composer.json` to that latest commit:

```json
"require": {
  "craftcms/cms": "dev-develop#c20adf2bca58d16a3adbe78b2ceef37b90947797 as 3.1.11",
  "...": "..."
}
```

Then run `composer update` in your terminal.

**Comment by brandonkelly** [comment]
We released 3.1.12 today with the fix.

**Comment by reganlawton** [comment]
@brandonkelly I experiencing this issues still on the latest build I need to be in `dev` env to run changes, I have `'allowAdminChanges' => false,` of non `dev` environments. Bit of an issue on our AWS Elastic Beanstalk setup where we need to change the ENV then deploy then change back.

Understandably its a WIP but if you need to see my project.yml hit me up on Discord. As it'd be nice to be able to deploy project sync changes to non `dev` environments.

**Comment by brandonkelly** [comment]
@reganlawton You should be able to search for the error in your `storage/logs/` folder, which will reveal the stack trace leading up to the error. Most likely it is going to be because a plugin isn’t following our guidance on [project config migrations](https://docs.craftcms.com/v3/extend/project-config.html#project-config-migrations).
