### ISSUE TITLE
Can't re-add a global set after removal

### ISSUE THREAD

**Issue by jurriaanr** [craftcms/cms#4091]
### Description
I removed a global set to fix a sync issue with the project.yml file. But when I want to add it again, I get an error that the handle and name already exists, which is true because they were never removed from the database. They should be, or I need the option to reenable them

### Steps to reproduce

1. Add global set
2. Remove globat set
3. Add again with the same name/handle

### Additional info

- Craft version: 3.1.20.1
- PHP version: 7.2.12
- Database driver & version: MySQL 5.6.43
- Plugins & versions: -

**Comment by brandonkelly** [comment]
Can you try running `./craft project-config/rebuild` from your terminal, and see if that fixes this?

**Comment by jurriaanr** [comment]
There is no relation with the project.yml, this will also happen on a complete clean install. I just installed a fresh install with composer create-project craftcms/craft. First thing I did after going through the setup was adding a global set with the name test. Then deleted it and tried to add a global set with the name test again. You will now get an error that the name and handle are already in use. "useProjectConfigFile" setting is false. 

(i did try to run the command btw, but as expected that does not fix it)

**Comment by juresrpcic** [comment]
Could be related to https://github.com/craftcms/cms/issues/4100 - project config might be re-creating the deleted global set.

**Comment by jurriaanr** [comment]
While it could be that it also happens there, this is really before any project.yml file is being used. useProjectConfigFile is false. I don't have the install on hand, but I don't think there even is a project.yml file for this reason.

**Comment by brandonkelly** [comment]
@jurriaanr Craft creates the project config internally whether you’ve enabled the `useProjectConfigFile` setting or not. But yeah, #4100 may have something to do with this; let’s try running that command once 3.2.22 is out next week.

**Comment by jurriaanr** [comment]
Fair enough, the global set is indeed present in the info table's config field. Will test after the release

**Comment by brandonkelly** [comment]
We released 3.1.22 today.

**Comment by jurriaanr** [comment]
I updated my install, but unfortunately the problem still exists. Tried running the rebuild command again as well, but no such luck

**Comment by brandonkelly** [comment]
@jurriaanr Can you send your `composer.json` and `composer.lock` files, and a database backup, over to support@craftcms.com? Reference this GH issue and include specific steps to reproduce based on your install.

**Comment by jurriaanr** [comment]
done

**Comment by brandonkelly** [comment]
This ended up being due to a validation conflict with the soft-deleted global set. Fixed for the next release!
