### ISSUE TITLE
Changed Matrix fields in drafts don't show up on edit screen since eb5dc9f

### ISSUE THREAD

**Issue by d--j** [craftcms/cms#4105]
### Description

The commit https://github.com/craftcms/cms/commit/eb5dc9f503863eb41f2d5fd1a46a49c91faa6c68 broke saving entry drafts with matrix fields. Changes to matrix fields do get saved to the draft (are part of the `[[entrydrafts.data]]` column's JSON) but they do not get shown on the edit form anymore and thus are lost when the draft will get re-saved or published.

### Steps to reproduce

1. Create a section with a matrix field (Use the Architect JSON to speed things up)
2. Create a new entry
3. Create a new draft for this entry, change or add something in a matrix field
4. Save the draft. Your changes to the matrix field are not there anymore on the edit screen.
5. Bonus (If you have a template assigned): Click "Share" and see your changes on the frontend.

### Additional info

- Craft version: 3.1.21 and 3.1.21.1
- PHP version: 7.2
- Database driver & version: MySQL
- Plugins & versions: not relevant

Here is an Architect JSON for your tests:
```json
{
    "fieldGroups": [
        "Common"
    ],
    "sections": [
        {
            "name": "Test Section",
            "handle": "testSection",
            "type": "structure",
            "enableVersioning": true,
            "maxLevels": null,
            "siteSettings": [
                {
                    "hasUrls": true,
                    "uriFormat": "test-section\/{slug}",
                    "template": "",
                    "enabledByDefault": true
                }
            ]
        }
    ],
    "fields": [
        {
            "group": "Common",
            "name": "Test Matrix",
            "handle": "testMatrix",
            "instructions": "",
            "type": "craft\\fields\\Matrix",
            "minBlocks": "",
            "maxBlocks": "",
            "localizeBlocks": false,
            "blockTypes": [
                {
                    "name": "Test Block",
                    "handle": "testBlock",
                    "fields": [
                        {
                            "required": false,
                            "name": "Test Field",
                            "handle": "testField",
                            "instructions": "",
                            "type": "craft\\fields\\PlainText",
                            "typesettings": {
                                "placeholder": "",
                                "code": "",
                                "multiline": "1",
                                "initialRows": "4",
                                "charLimit": "",
                                "columnType": "text"
                            }
                        }
                    ]
                }
            ]
        }
    ],
    "entryTypes": [
        {
            "sectionHandle": "testSection",
            "name": "Test Section",
            "handle": "testSection",
            "hasTitleField": true,
            "titleLabel": "Titel",
            "titleFormat": "",
            "fieldLayout": {
                "Tab 1": [
                    "testMatrix"
                ]
            }
        }
    ]
}
```

**Comment by brandonkelly** [comment]
Thanks for reporting that and tracking down the culprit! Fixed for the next release.

**Comment by EFWall** [comment]
Hello @brandonkelly and everyone -- I still experience this problem in at least the following situation -- 

When the field is inside a matrix block which is a part of a matrix that is inside a Super Table which is, itself, inside a block of a matrix.

I haven't tested all possible combinations of super tables and matrix fields. I will report back if I get further specificity. But for now, I wanted to report there are still issues in these more complex field structures (our site contains a LOT of these). 

Any thoughts?

**Comment by d--j** [comment]
@EFWall did you update Super Table to [2.1.17+](https://github.com/verbb/super-table/releases/tag/2.1.17) Super Table fields had the same bug as Matrix field – that should have been fixed in that version.

**Comment by EFWall** [comment]
@d--j yes we are on SuperTable 2.1.17. However, I see they just posted 2.1.18 and it claims to fix an issue related to SuperTables nested inside matrix fields. We will update to that version and see if it resolves the issue.

**Comment by EFWall** [comment]
@d--j @brandonkelly we just updated to Craft 3.1.24 and SuperTable 2.1.18 and the issue still persists.

**Comment by brandonkelly** [comment]
@EFWall can you send in your `composer.json` and `composer.lock` files, and a database backup, to support@craftcms.com ?

**Comment by EFWall** [comment]
@brandonkelly done. Thanks!
