### ISSUE TITLE
Volume object not found when using S3 volumes

### ISSUE THREAD

**Issue by tinchalamo** [craftcms/cms#4329]
### Description
Having issues with assets stored in S3. It seems like Craft is losing track of assets being uploaded to S3.

**First issue** happened on publishing an entry where I got a "file not found path" error even though the image and path do exist:

![image](https://user-images.githubusercontent.com/11000310/58561592-0c978680-81ed-11e9-83fc-01e11a79d75f.png)

**Second issue** happened on uploading an asset where I got a "could not open stream" error:

![image](https://user-images.githubusercontent.com/11000310/58561638-26d16480-81ed-11e9-9597-01d6289c583b.png)

**Third issue** is that assets for current entries are now showing broken image:

![image](https://user-images.githubusercontent.com/11000310/58566216-ce529500-81f5-11e9-81b1-9850e763161d.png)

[Here's the stacktrace](https://gist.github.com/tinchalamo/2884c4e9782f0691152d845555a6e78b).

### Steps to reproduce

1. Create a new entry
2. Add assets to an entry
3. Try to publish entry

### Additional info

- Craft version: Craft CMS 3.2.0-alpha.7
- PHP version: 7.3.2
- Database driver & version: MySQL 5.6.34

**Comment by brandonkelly** [comment]
Sounds like this may have been resolved by 53f00211fe868b3935f14cce7ef713f00b59002e

**Comment by tinchalamo** [comment]
@brandonkelly looks like this is still an issue if using `{owner.id}` inside of a matrix block field. Asset fields on an entry are using the correct id, but any asset field inside of a matrix block is usinf the draft id.

**Comment by brandonkelly** [comment]
@tinchalamo Thanks, fixed via caf19a70b47a6b98b5493487521bf7d81934e6ce
