### ISSUE TITLE
[3.2] Add ability to set a default Preview Target

### ISSUE THREAD

**Issue by stursby** [craftcms/cms#4520]
### Description

I'd love to have the option (possibly in the Section Settings) to select a default Preview Target.

Currently, it defaults to "Primary entry page", which if I'm using Craft headless, I'd prefer the preview to not use the Twig template.

![D_IGeVTW4AAfPvO](https://user-images.githubusercontent.com/527849/60987589-8ac86c00-a307-11e9-9520-70b140e224f3.png)

### Steps to reproduce

N/A

### Additional info

- Craft version: 3.2

**Comment by minyangu-bgl** [comment]
Same here. We use Craft in headless fashion and do not use any twig template, so the local preview doesn't make sense here, instead, we wish to set the default preview target to our remote site which consumes content from Craft.

**Comment by stursby** [comment]
@minyangu-bgl I was just using Local for my demo, but yes, being able to set something other than the Twig default template is what I'm looking for!

**Comment by ryanpcmcquen** [comment]
Related: https://github.com/craftcms/cms/issues/4652

**Comment by stursby** [comment]
@brandonkelly This might be obsolete now with the release of 3.3 since after setting `'headlessMode' => true` in `configs/general.php` the first Preview Target becomes the default.

**Comment by brandonkelly** [comment]
You’d get the same behavior without Headless Mode if you just left your section’s URI format blank.

**Comment by brandonkelly** [comment]
Seems like all the use cases for this are when using Craft as a headless CMS, in which case you shouldn’t even be setting entry URI formats (and you don’t even have the option to set that if you enable [headlessMode](https://docs.craftcms.com/v3/config/config-settings.html#headlessmode) in v3.3).

**Comment by stursby** [comment]
@brandonkelly Yep, makes sense. Will the 3.2/3.3 additions, I think that solved the issue. Thanks for the great releases! 🙌🏻

**Comment by lmounsey** [comment]
@brandonkelly Is there some way to achieve this without running in headless mode?

I'm creating a Nuxt/CraftCMS stack atm - whilst it is technically a headless CMS, I'm utilising the entry URI formats as well as the `uri` field in GraphQL to determine my page structure (which get's removed if I have enabled headless mode).

I suppose I could use the build this using slug/parent but would be a nightmare  doing this through my entire web app.

Preview actually works fine now (pointing to my web app as the base URL), but Im thinking in production we may want a different site to host an SPA of the app for preview, then have a statically generated site for live. Would be great if there was a general settings options to override the preview base URL

**Comment by brandonkelly** [comment]
@lmounsey I’d suggest creating a custom field to store the URIs, perhaps using a [Preparse](https://plugins.craftcms.com/preparse-field) field so that the actual value can still be based on a dynamic template.

**Comment by brandonkelly** [comment]
Alright that’s all been done for Craft 3.4!

If you have a noncritical project you want to test it out on, change your `craftcms/cms` requirement in composer.json to:

```json
"require": {
  "craftcms/cms": "3.4.x-dev",
  "...": "..."
}
```

Then run `composer update`.

**Comment by diluno** [comment]
I know get this error when adding a URI to a section in headless mode:
`Undefined index: template`

**Comment by brandonkelly** [comment]
@diluno Sorry about that, fixed now.

**Comment by lmounsey** [comment]
Hi @brandonkelly 

I'm testing out `3.4.x-dev` and I'm getting a "null" result on the `uri` when querying my entries in GraphQL - section URI formats have been set - is there anything else I need to do to get this to work?

**Comment by brandonkelly** [comment]
@lmounsey Just pushed 900b262e1c636f029934ca025a9d0e21c58863d5 which should fix that. Run `composer update` again.

**Comment by Jones-S** [comment]
@lmounsey I just read that you have a running preview in a headless setup. I have (had) the following approach, where graphql was not out as a core service yet:
- Open the frontend app in the preview window
- Using the preview token to send a graphql request to retrieve the latest draft of that entry (needing the slug, which was set correctly back then)
- rendering the content with the draft data.

Is this kind of the thing you do, or could you quickly point out the differences? That would be very much appreciated.
also I am experiencing sudden problems with the slug. 

`src="http://localhost:3000/seomatic/preview-social-media?elementId=26&siteId=1&x-craft-live-preview=JGAI1djkAp&token=tR0zbfcgzS8PL8m1_xTyvMpotWGWDpys"`

is a current iframe src link from a craft preview.
The slug is very weird, I have no idea where that is originating from (obviously from the use of the seomatic plugin... but nevertheless this is weird).
So how would you get the correct slug to query the correct entry (page)?

**Comment by Jones-S** [comment]
@brandonkelly 
could it be that the `uri` is not yet exposed via GraphQl? I still get `null` when querying it.
Also I would wonder how I could use a preview URL like:

<img width="1410" alt="image" src="https://user-images.githubusercontent.com/7059580/66765776-e9742780-eeac-11e9-9c5c-fd893779f580.png">
The problem with this is, when I don't have a nested page (I am using `structures` as sections), I get a uri like `localhost:3000//slug` – how could I make the first slash depending on the existence of a parent?
Thank you in advance

**Comment by brandonkelly** [comment]
@Jones-S Doh, sorry! Just fixed a couple remaining issues with headless mode + element URIs (e69c4d35d4e38ae7a842cc268ff68a3438c76c5d). Run `composer update` now, resave your entries, and you should be good to go.

**Comment by lmounsey** [comment]
> @lmounsey I just read that you have a running preview in a headless setup. I have (had) the following approach, where graphql was not out as a core service yet:
> 
> * Open the frontend app in the preview window
> * Using the preview token to send a graphql request to retrieve the latest draft of that entry
> * rendering the content with the draft data.
> 
> Is this kind of the thing you do, or could you quickly point out the differences? That would be very much appreciated.

Yep that's right - seems to mostly work well, except then switching the entry type to an existing entry, the preview still thinks it's using the the old entry type (until I resave the entry). It's not a massive issue though as it would be pretty rare in my case.

**Comment by Jones-S** [comment]
@brandonkelly thanks for the update. works like a charm now 👍 
@lmounsey thank you for your input, now I know that I am on the right path :). And I think that limitation, you mention, is ok.

**Comment by khalwat** [comment]
yas... I need this for SEOmatic https://github.com/nystudio107/craft-seomatic/issues/485

**Comment by khalwat** [comment]
```php
    /**
     * Returns an element by its URI.
     *
     * @param string $uri The element’s URI.
     * @param int|null $siteId The site to look for the URI in, and to return the element in.
     * Defaults to the current site.
     * @param bool $enabledOnly Whether to only look for an enabled element. Defaults to `false`.
     * @return ElementInterface|null The matching element, or `null`.
     */
    public function getElementByUri(string $uri, int $siteId = null, bool $enabledOnly = false)
    {
        if (Craft::$app->getConfig()->getGeneral()->headlessMode) {
            return null;
        }
```

^ will the above be changed as well? SEOmatic depends on this to find the matched element for a given URI; I realize this may be in there to prevent things down the chain from loading in an element.

Perhaps an additional `force` param that defaults to false, in cases where we need this? Feels gross, but the alternative is that I end up doing copy pasta on this method :)

**Comment by brandonkelly** [comment]
@khalwat yeah, already removed in e69c4d35d4e38ae7a842cc268ff68a3438c76c5d

**Comment by khalwat** [comment]
mmmm I should have looked at the diff more closely, sorry! Awesome news!

**Comment by JensvdHeydt** [comment]
I'm sorry but could somebody explain how to use this feature exactly?

I'm running craft in headless mode, using the 3.4-dev Branch and I'm currently trying to Query the URL of  my Sites Pages (inside a structure) and url and uri both are null in the GraphQL responses.

**Comment by brandonkelly** [comment]
@JensvdHeydt probably best if you post your question (with some more details) over at https://craftcms.stackexchange.com/.
