### ISSUE TITLE
Plugin license won't detach

### ISSUE THREAD

**Issue by darylknight** [craftcms/cms#4525]
I'm trying to detach a plugin from a Craft install using the Craft ID website. When I click "Detach from this Craft license", it works. Then when I visit the list of plugins in my local development site and go back to the Craft ID website, it's re-attached itself.

Posted this too early - but it looks like this can be fixed by _first_ removing the key from the plugin on the list of plugins, _then_ detaching it on the Craft ID website.

**Comment by brandonkelly** [comment]
Right – plugin licenses automatically attach themselves to the Craft license whenever an API request comes in that shows that they are being used together.

**Comment by k7y6t5** [comment]
Sorry to bring up old stuff, but I'm still having trouble understanding the order of operations. 

@darylknight says "this can be fixed by first removing the key from the plugin on the list of plugins." Unless I'm misunderstanding, this means that I should release the plugin license before removing the plugin license from our Craft license. I've released the plugin license but am now unable to remove the plugin from our Craft license.

I then reclaimed the plugin license, detached it from our Craft license, and then released the plugin license. That didn't work either.

**Comment by brandonkelly** [comment]
By that he was referring to the key in the Settings → Plugins page within your control panel.

**Comment by k7y6t5** [comment]
I don't know why I'm having so much trouble with this. The plugin is currently installed and active. The options I see in Settings > Plugins are Disable and Uninstall. I don't see any way to remove the key. Is that because the plugin has expired? 

![image](https://user-images.githubusercontent.com/2165930/87434671-bdf7a800-c5b8-11ea-8ace-f8f77678eff9.png)

**Comment by brandonkelly** [comment]
@k7y6t5 Looks like there was a bug where it wasn’t possible to remove a plugin license for a disabled/uninstalled plugin. I’ve just fixed that for the next release. Once you’ve updated, you will be able to select your license key and delete it from that page. (Or if you’re in a hurry, install the plugin first, then delete its license key, then uninstall.)

**Comment by brandonkelly** [comment]
Craft 3.4.28 is out now with this fix.

**Comment by k7y6t5** [comment]
Err, I still can't figure out how to delete the plugin key after updating to 3.4.28.1. I don't see any option for managing the plugin's key in the CP. If it makes a difference, I have logged into Craft ID in the CP. Is the ability to delete the key a function of the plugin or of Craft?

![how-to-delete-key](https://user-images.githubusercontent.com/2165930/87734389-8186a080-c7a0-11ea-901f-cabf2bc627b4.jpg)

**Comment by brandonkelly** [comment]
@k7y6t5 Just select the key in the input (what you have redbox’d in your screenshot) and delete it.

**Comment by k7y6t5** [comment]
I feel like I've never used a computer before. The thing I have in red is text. Selecting the text and hitting Delete takes me back a page. If I select the text and right click, Delete is greyed out. Here's the HTML:

`<input class="text code" size="29" maxlength="29" value="XXXX-XXXX-XXXX-XXXX-XXXX-XXXX" readonly="readonly" disabled="disabled">`

**Comment by brandonkelly** [comment]
Are you getting any JS errors on the page? And try opening your browser’s Network tab, and then reloading the page – are you seeing any unresolved or non-2xx Ajax requests getting logged?

**Comment by k7y6t5** [comment]
No JS errors, no non-2xx Ajax requests.

And I should mention that I really appreciate all the help here. I don't know what's going on but either I'm horribly misunderstanding something really simple or there's something wonky happening.

**Comment by brandonkelly** [comment]
Can you try with the plugin installed? Any difference?

**Comment by k7y6t5** [comment]
Well blow me down! Installing the plugin allowed me to select the license key and delete it. I just didn't know that that was the process for removing a plugin license from within the CP.

I think this is the order of operations:
1. In the CP, go to Settings > Plugins
2. While the plugin is installed, select the plugin's license key text and delete it
3. Log in to id.craftcms.com and go to Licenses > Plugins to find the plugin
4. Under License Details > Craft License, detach the plugin from the appropriate Craft license
5. Back in the CP, go to Settings > Plugins and use the gear icon to Uninstall the plugin
6. Once the uninstall process has finished, use the gear menu to Remove the plugin

Thanks @brandonkelly!
