### ISSUE TITLE
Db::parseParam seach for null or 0 values

### ISSUE THREAD

**Issue by Anubarak** [craftcms/cms#5073]
### Description
I used to search for inactive lightswitches in Craft via `field(['or', null, 0])` since MySql does not return `null` rows via `<> 1` you need to seach for `!= 1 AND NOT NULL`.
That worked great until one of the last releases of Craft where `Db::parseParam` does not include 0 values anymore with that string.

Earlier releases of Craft did this

```PHP
Db::parseParam('test', ['or', 0, null])

// array 
array(3) {
  [0]=>
  string(2) "or"
  [1]=>
  array(3) {
    [0]=>
    string(2) "or"
    [1]=>
    array(1) {
      ["test"]=>
      NULL
    }
    [2]=>
    array(1) {
      ["test"]=>
      string(0) ""
    }
  }
  [2]=>
  array(3) {
    [0]=>
    string(2) "in"
    [1]=>
    string(4) "test"
    [2]=>
    array(1) {
      [0]=>
      int(0)
    }
  }
}
```
```SQL
((`content`.`field_test` IS NULL) OR (`content`.`field_test`='')) OR (`content`.`field_test`=0))
```
The current version of Craft does this
```
Db::parseParam('test', ['or', 0, null])

// array
array(3) {
  [0]=>
  string(2) "or"
  [1]=>
  array(3) {
    [0]=>
    string(2) "or"
    [1]=>
    array(1) {
      ["test"]=>
      NULL
    }
    [2]=>
    array(1) {
      ["test"]=>
      string(0) ""
    }
  }
  [2]=>
  array(1) {
    ["test"]=>
    int(0)
  }
}
```
```SQL
((NOT (`content`.`field_test`=TRUE)) OR (NOT (`content`.`field_test`=TRUE))
```

So it's slightly different. In my case it returns quite the opposite elements which resultet in fatal errors. I would like to know if this change is intended or a mistake? Do I have to search for all such references in my code and change them to
```PHP
->andWhere(['or', ['=', 'field_test', 0], ['IS', 'field_test',  null]])
```
and work in Yii2 level?

### Additional info

- Craft version: 3.3.8
- PHP version: 7.3

**Comment by brandonkelly** [comment]
Within an element query, you should have always just been passing `true` or `false` to the field’s param:

```php
$entry = Entry::find()
    ->lightswitchFieldHandle(false)
    ->all();
```

(Other syntaxes were supported as well: `0`, `1`, `'0'`, `'1'`, `:empty:`, `:notempty:`, `'not 1'`.)

We have fixed a couple issues with querying for elements by their lightswitch values in the past few releases (#4939 and then #5046), which would have impacted how `Db::parseParam()` should be used in conjunction with a Lightswitch field column, for manually-assembled queries. So as of Craft 3.3.8, here’s what you should do:

```php
$query->andWhere(Db::parseParam('field_test', false, '=', false, \yii\db\Schema::TYPE_BOOLEAN));
```

**Comment by Anubarak** [comment]
But passing `true` or `false` still fails because I would like to have all that are `null` *or* `0`
passing `true` will give me all that are true, passing  `false` will return all that are `false` but in case the lightswitch field is not resaved they are `null` and neither of those will fetch null results.

Furthermore if the field is only in one layout and not in the other one (different entry types or something) this won't work as well.
I would honestly prefere the previous way.

The other way would be to add `not null` when you do `field('not 1')`

**Comment by brandonkelly** [comment]
If you pass `Schema::TYPE_BOOLEAN` into that last argument of `parseParam()`, `false` will actually end up becoming `['not', ['field_test' => true]]`, meaning any rows where the value isn’t set to `true` (or `1` if this is MySQL), so that includes `null` values as well.

https://github.com/craftcms/cms/blob/900b262e1c636f029934ca025a9d0e21c58863d5/src/helpers/Db.php#L487-L496

**Comment by brandonkelly** [comment]
Sorry you’re right. I had tested this earlier but my test was flawed.

Fixed now for the next release.

To get the fix early, change your `craftcms/cms` requirement in composer.json to:

```json
"require": {
  "craftcms/cms": "dev-develop#bbe7e293e6a38864b1dd79d1e70760bb148be535 as 3.3.9",
  "...": "..."
}
```

Then run `composer update`.
