### ISSUE TITLE
Upgrading to Craft 3.3.17 from 3.1.34.2 requires manual deletion of userpermissions

### ISSUE THREAD

**Issue by ryanpcmcquen** [craftcms/cms#5312]
### Description
```
bash-5.0$ ./craft migrate/all
Yii Migration Tool (based on Yii v2.0.30)

    > insert into {{%userpermissions}} ... done (time: 0.014s)
    > insert into {{%userpermissions}} ... done (time: 0.002s)
    > insert into {{%userpermissions}} ... done (time: 0.001s)
    > insert into {{%userpermissions}} ... done (time: 0.002s)
    > insert into {{%userpermissions}} ... done (time: 0.001s)
    > insert into {{%userpermissions}} ... done (time: 0.001s)
    > insert into {{%userpermissions}} ... done (time: 0.004s)
    > insert into {{%userpermissions}} ... done (time: 0.002s)
    > insert into {{%userpermissions}} ... done (time: 0.002s)
    > insert into {{%userpermissions}} ... done (time: 0.001s)
    > insert into {{%userpermissions}} ...Exception: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'editimagesinvolume:a4a748d1-f757-4bc3-bf15-0991736adeb8' for key 'userpermissions_name_unq_idx'
The SQL being executed was: INSERT INTO `userpermissions` (`name`, `dateCreated`, `dateUpdated`, `uid`) VALUES ('editimagesinvolume:a4a748d1-f757-4bc3-bf15-0991736adeb8', '2019-12-05 22:48:06', '2019-12-05 22:48:06', 'b8be452b-f54d-48cf-b18e-647419a57cae') (/var/www/html/vendor/yiisoft/yii2/db/Schema.php:674)
#0 /var/www/html/vendor/yiisoft/yii2/db/Command.php(1295): yii\db\Schema->convertException(Object(PDOException), 'INSERT INTO `us...')
#1 /var/www/html/vendor/yiisoft/yii2/db/Command.php(1091): yii\db\Command->internalExecute('INSERT INTO `us...')
#2 /var/www/html/vendor/craftcms/cms/src/db/Migration.php(216): yii\db\Command->execute()
#3 /var/www/html/vendor/craftcms/cms/src/migrations/m190417_085010_add_image_editor_permissions.php(37): craft\db\Migration->insert('{{%userpermissi...', Array)
#4 /var/www/html/vendor/craftcms/cms/src/db/Migration.php(58): craft\migrations\m190417_085010_add_image_editor_permissions->safeUp()
#5 /var/www/html/vendor/craftcms/cms/src/db/MigrationManager.php(239): craft\db\Migration->up(true)
#6 /var/www/html/vendor/craftcms/cms/src/db/MigrationManager.php(159): craft\db\MigrationManager->migrateUp(Object(craft\migrations\m190417_085010_add_image_editor_permissions))
#7 /var/www/html/vendor/craftcms/cms/src/services/Updates.php(230): craft\db\MigrationManager->up()
#8 /var/www/html/vendor/craftcms/cms/src/console/controllers/MigrateController.php(265): craft\services\Updates->runMigrations(Array)
#9 [internal function]: craft\console\controllers\MigrateController->actionAll()
#10 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#11 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#12 /var/www/html/vendor/yiisoft/yii2/console/Controller.php(164): yii\base\Controller->runAction('all', Array)
#13 /var/www/html/vendor/yiisoft/yii2/base/Module.php(528): yii\console\Controller->runAction('all', Array)
#14 /var/www/html/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('migrate/all', Array)
#15 /var/www/html/vendor/craftcms/cms/src/console/Application.php(93): yii\console\Application->runAction('migrate/all', Array)
#16 /var/www/html/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('migrate/all', Array)
#17 /var/www/html/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(craft\console\Request))
#18 /var/www/html/craft(22): yii\base\Application->run()
#19 {main}
Exception 'craft\errors\MigrateException' with message 'An error occurred while migrating Craft CMS.'

in /var/www/html/vendor/craftcms/cms/src/services/Updates.php:246

Stack trace:
#0 /var/www/html/vendor/craftcms/cms/src/console/controllers/MigrateController.php(265): craft\services\Updates->runMigrations(Array)
#1 [internal function]: craft\console\controllers\MigrateController->actionAll()
#2 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#3 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#4 /var/www/html/vendor/yiisoft/yii2/console/Controller.php(164): yii\base\Controller->runAction('all', Array)
#5 /var/www/html/vendor/yiisoft/yii2/base/Module.php(528): yii\console\Controller->runAction('all', Array)
#6 /var/www/html/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('migrate/all', Array)
#7 /var/www/html/vendor/craftcms/cms/src/console/Application.php(93): yii\console\Application->runAction('migrate/all', Array)
#8 /var/www/html/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('migrate/all', Array)
#9 /var/www/html/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(craft\console\Request))
#10 /var/www/html/craft(22): yii\base\Application->run()
#11 {main}
```

### Steps to reproduce

1. Have `editimagesinvolume:` entries in the `userpermissions` table.
2. Upgrade from Craft 3.1.x to 3.3.17.

### Additional info

- Craft version: 3.3.17
- PHP version: 7.3.x

**Comment by brandonkelly** [comment]
Can you send your `composer.json` and `composer.lock` files, plus a database backup from before you attempted the 3.3 upgrade, over to support@craftcms.com?

**Comment by brandonkelly** [comment]
Sorry, I was just reminded that this bug was fixed in 3.1.34.3. Please do this:

1. Restore a DB backup from 3.1.34.2
2. Update to 3.1.34.3
3. Run `./craft project-config/rebuild`
4. Finally, update to Craft 3.3.

**Comment by ryanpcmcquen** [comment]
OK.

**Comment by ryanpcmcquen** [comment]
That workflow did not work, unfortunately. Manual database intervention is still required. It seems that 3.1.34.3 does not actually fix this issue.

**Comment by brandonkelly** [comment]
If you send a database backup and your `composer.json` and `composer.lock` files (from before the update), we can look into it.
