### ISSUE TITLE
Error upgrading from 3.4.0-beta.5 to RC1.1

### ISSUE THREAD

**Issue by RyanRoberts** [craftcms/cms#5443]
### Description

I'm getting the following error message when attempting to upgrade the version mentioned in the title:

``` 
Performing update with Composer ... error: An error occurred

Output:

<warning>Package "craftcms/vue-asset" listed for update is not installed. Ignoring.</warning>
<warning>Package "danielstjules/stringy" listed for update is not installed. Ignoring.</warning>
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - don't install zendframework/zend-feed 2.12.0|don't install laminas/laminas-feed 2.12.0
    - don't install laminas/laminas-feed 2.12.0|remove zendframework/zend-feed 2.12.0
    - don't install laminas/laminas-feed 2.12.0|don't install zendframework/zend-feed 2.12.0
    - craftcms/cms 3.4.0-RC1.1 requires laminas/laminas-feed ^2.12.0 -> satisfiable by laminas/laminas-feed[2.12.0].
    - Installation request for craftcms/cms 3.4.0-RC1.1 -> satisfiable by craftcms/cms[3.4.0-RC1.1].
    - Installation request for zendframework/zend-feed (locked at 2.12.0) -> satisfiable by zendframework/zend-feed[2.12.0].

<warning>Running update with --no-dev does not mean require-dev is ignored, it just means the packages will not be installed. If dev requirements are blocking the update you have to resolve those problems.</warning>
```

I'm not sure how to resolve this 🤔

### Additional info

- Craft version: 3.4.0-beta.5
- PHP version: 7.4.1
- Database driver & version: mysql@5.7
- Plugins & versions: Amazon S3 1.2.7,  CP Field Inspect 1.0.7, Express Forms 1.0.4, Redactor 2.4.0, Super Table 2.3.2, Cookie Consent Banner 1.1.6, Mailgun 1.4.2, Typed link field 1.0.19

**Comment by brandonkelly** [comment]
Do you have `zendframework/zend-feed` listed as a requirement in your `composer.json` file? Can you post the full contents of your `composer.json`?

**Comment by bencroker** [comment]
Running `composer update` should resolve this issue.

**Comment by RyanRoberts** [comment]
> Do you have `zendframework/zend-feed` listed as a requirement in your `composer.json` file? Can you post the full contents of your `composer.json`?

@brandonkelly  here it is:

```
{
  "require": {
    "adigital/cookie-consent-banner": "1.1.6",
    "craftcms/aws-s3": "1.2.7",
    "craftcms/cms": "3.4.0-beta.5",
    "craftcms/mailgun": "1.4.2",
    "craftcms/redactor": "2.4.0",
    "mmikkel/cp-field-inspect": "1.0.7",
    "sebastianlenz/linkfield": "1.0.19",
    "solspace/craft-express-forms": "1.0.4",
    "verbb/super-table": "2.3.2",
    "vlucas/phpdotenv": "^3.4.0"
  },
  "autoload": {
    "psr-4": {
      "modules\\": "modules/"
    }
  },
  "config": {
    "sort-packages": true,
    "optimize-autoloader": true,
    "platform": {
      "php": "7.0"
    }
  },
  "scripts": {
    "post-root-package-install": [
      "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
    ]
  }
}
```

@bencroker That didn't appear to fix it, but I do get the following…

```
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Package zendframework/zend-escaper is abandoned, you should avoid using it. Use laminas/laminas-escaper instead.
Package zendframework/zend-feed is abandoned, you should avoid using it. Use laminas/laminas-feed instead.
Package zendframework/zend-stdlib is abandoned, you should avoid using it. Use laminas/laminas-stdlib instead.
Generating optimized autoload files
Carbon 1 is deprecated, see how to migrate to Carbon 2.
https://carbon.nesbot.com/docs/#api-carbon-2
    You can run './vendor/bin/upgrade-carbon' to get help in updating carbon and other frameworks and libraries that depend on it.```

**Comment by brandonkelly** [comment]
I’m able to reproduce this when attempting to update to 3.4 RC1 from Beta 5. Will get it fixed…

**Comment by brandonkelly** [comment]
Fixed now! Try updating again, should work this time.

**Comment by RyanRoberts** [comment]
Thanks
