### ISSUE TITLE
Craft 3.4.0 RC 1.1: Matrix min and max block saving validation error

### ISSUE THREAD

**Issue by Wiejeben** [craftcms/cms#5455]
### Description
When having a matrix block configured with minimum of 1 and maximum of 1 blocks it fails on saving an entry.

The following error is returned: "Test input should contain at least 1 block."

### Steps to reproduce

1. Create matrix input field with min and max set to 1
2. Add field to entry
3. Save entry with matrix block filled as expected

### Additional info

- Craft version: 3.4.0 RC 1.1
- PHP version: PHP 7.2.26
- Database driver & version: MySQL 5.7
- Plugins & versions: Clean install

**Comment by brandonkelly** [comment]
Thanks for reporting that! Fixed now for the next 3.4 release.

To get the fix early, change your `craftcms/cms` requirement in composer.json to:

```json
"require": {
  "craftcms/cms": "3.4.x-dev#fe99410a6199a75317155f5090c0a8862696ffc3 as 3.4.0-RC1.1",
  "...": "..."
}
```

Then run `composer update`.

**Comment by willard** [comment]
Still not working on latest version

<img width="800" alt="2020-02-20_1055" src="https://user-images.githubusercontent.com/544756/74977189-400fe600-53f8-11ea-98a9-b9c257badf9d.png">



Craft edition & version | Craft Pro 3.4.6.1

**Comment by brandonkelly** [comment]
@willard We just released Craft 3.4.7 with a better fix. Let me know how it goes.

**Comment by willard** [comment]
Thank you.. on latest released Craft 3.4.7 fixed it..

**Comment by jlabs** [comment]
Not sure if this is still an issue, but we're getting the same error.
Install specs are:

- Craft version: 3.4.27
- PHP version: PHP 7.2.32
- Database driver & version: MySQL 5.6.47
- Plugins & versions: 
  - Assets Usage: 2.1.0
  - CKEditor: 1.0.0 Beta 3
  - Contact Form: 2.2.7
  - Fetch: 1.3.0
  - Instagram Feed: 1.0.5
  - Redactor: 2.6.1
  - Redirect: 1.0.23
  - SuperSort: 3.0.1
  - Super Table: 2.5.1
  - Table Maker: 2.0.1
