### ISSUE TITLE
[3.4] Vue tables don't display html entities properly

### ISSUE THREAD

**Issue by Mosnar** [craftcms/cms#5532]
### Description
In the "Sections" settings, one of my section titles has an ampersand in it and it is being displayed as `&amp;` in the table. Clicking into the section settings displays the "&" properly.

### Steps to reproduce

1. Create a section in the CP with an "&"
2. Look at Sections list

### Additional info

- Craft version: 3.4.0.2
- PHP version: 7.3
- Database driver & version: MySQL 8
- Plugins & versions: N/A

**Comment by Mosnar** [comment]
Just noticed Github parsed my `&amp;` so my issue looks non-sensical. But I'm sure you figured out what I meant 😉

**Comment by brandonkelly** [comment]
Yeah we’re able to reproduce. Karma for all the times I’ve reported the same bug to other services due to `Pixel &amp; Tonic` :)

**Comment by nfourtythree** [comment]
Hi @Mosnar 

This has been fixed in the reference commit and will be included in the next release.

Thanks!

**Comment by brandonkelly** [comment]
Craft 3.4.2 is out with the fix for this.

**Comment by pixelmachine** [comment]
@brandonkelly I think maybe you've missed one.

I'm running 3.4.3 and I'm still seeing this on the Sections -> Entry Types table. 
It's fine elsewhere.

**Comment by brandonkelly** [comment]
Looks like @nfourtythree fixed that in 2f565da0d598591df01b7ada18e8990124e495f9.

**Comment by brandonkelly** [comment]
Craft 3.4.4 is out now with that fix.
