### ISSUE TITLE
BaseOptionsField.php error

### ISSUE THREAD

**Issue by LouisCuvelier** [craftcms/cms#5533]
### Description

After upgrading to 3.4, I'm facing this issue. It's similar to #5014

```log
2020-01-29 16:41:25 [-][1][jn2lalrtblm1vm3k0un961ap4d][error][RuntimeException] yii\base\ErrorException: Undefined index: value in /home/coursierjob-staging/webapps/coursierjob-staging/vendor/craftcms/cms/src/fields/BaseOptionsField.php:427
```

### Steps to reproduce

1. Update to Craft 3.4
2. Open an entry with a dropdown field

### Additional info

- Craft version: 3.4.0.2
- PHP version: 7.3.13
- Database driver & version: MySQL 5.5.5
- Plugins & versions:
```json
{
    "aelvan/imager": "v2.3.1",
    "aelvan/preparse-field": "v1.1.0",
    "codemonauts/craft-redactor-nofollow": "1.0.0",
    "craftcms/anchors": "2.2.0",
    "craftcms/cms": "3.4.0.2",
    "craftcms/redactor": "2.5.0",
    "craftsnippets/table-of-contents": "1.0.2",
    "doublesecretagency/craft-upvote": "2.0.4",
    "ether/simplemap": "3.7.7",
    "jalendport/craft-readtime": "1.6.0",
    "mmikkel/retcon": "2.0.12",
    "nesbot/carbon": "^2.23.1",
    "nystudio107/craft-disqus": "1.1.2",
    "nystudio107/craft-eagerbeaver": "1.0.4",
    "nystudio107/craft-emptycoalesce": "1.0.6",
    "nystudio107/craft-minify": "1.2.9",
    "nystudio107/craft-retour": "3.1.33",
    "nystudio107/craft-seomatic": "3.2.39",
    "nystudio107/craft-templatecomments": "1.1.2",
    "nystudio107/craft-typogrify": "^1.1",
    "putyourlightson/craft-blitz": "3.1.1",
    "topshelfcraft/supersort": "3.0.1",
    "verbb/field-manager": "2.1.1",
    "verbb/image-resizer": "2.0.6",
    "verbb/super-table": "2.4.0",
    "vlucas/phpdotenv": "^3.6",
    "wrav/oembed": "1.1.8"
}
```

**Comment by brandonkelly** [comment]
Can you please send a database backup from before updating to Craft 3.4, plus your `composer.json` and `composer.lock` files, over to support@craftcms.com , and reference this issue URL + where the error is occurring?

**Comment by LouisCuvelier** [comment]
Done 😊

**Comment by LouisCuvelier** [comment]
Ok with the help of @olivierbon, I found a solution.

I don't know why, but after updating to 3.4, the folder /storage/config-deltas was pushed on the git server even with the .gitignore.

So all my dropdown fields were empty on my staging and prod server.

Removing config-deltas from git, rebuilding project config and pushing again fix the whole thing.

Thanks for your help 😊

**Comment by brandonkelly** [comment]
Going to close this since we haven’t been able to reproduce, even with your files. We can continue to help offline though.

**Comment by brandonkelly** [comment]
Glad you got it sorted!

**Comment by henrypenny** [comment]
I've encountered the same problem. I've tried doing the rebuild and still have an error.

In BaseOptionsField.php line 427:

`                if (!isset($option['optgroup']) && (string)$option['value'] === $value) {`

The code is looking for `$option['value']`, however `$option` looks like this:

```array (
  '__assoc__' => 
  array (
    0 => 
    array (
      0 => 'label',
      1 => 'Default',
    ),
    1 => 
    array (
      0 => 'value',
      1 => 'default',
    ),
    2 => 
    array (
      0 => 'default',
      1 => '1',
    ),
  ),
)```

**Comment by brandonkelly** [comment]
@henrypenny same request to you, then: https://github.com/craftcms/cms/issues/5533#issuecomment-579915799

**Comment by henrypenny** [comment]
I've sent those to support.
Thanks.

**Comment by jaspertandy** [comment]
Just want to add on that I've experienced what looks to be the same issue as @henrypenny above, and I'm not quite sure what the real fix is. Fortunately for me, the field was supposed to be a text field anyway, but converting from a dropdown to a text field left the options in my project.yaml, so if this happens to you, maybe just delete those options and sync should run (unless you also have other problems!)

**Comment by brandonkelly** [comment]
@ostark do you happen to have a DB backup from before you deleted the widget? If not, are you able to reproduce the error again if you re-add the widget with the same settings?

**Comment by ostark** [comment]
@brandonkelly looks like I have a DB backup (after update, before removing the widget).

**Comment by brandonkelly** [comment]
I was able to reproduce this with @ostark’s backup. Somehow, some of the associative arrays within the project config got double-packed as `__assoc__` arrays.

I’ve added a guard against that, so associative arrays that already contain an `__assoc__` key won’t get double-packed, and I’ve added a new `utils/repair/project-config` command that you can run to clean up any existing double-packed arrays.

**Comment by davidhellmann** [comment]
When I run `utils/repair/project-config` my Project Config do changes like this:
![image](https://user-images.githubusercontent.com/764292/86499901-dfbd8780-bd8d-11ea-844c-52a942c26324.png)

But when I run `project-config/rebuild` it becomes reversed?
![image](https://user-images.githubusercontent.com/764292/86499921-04196400-bd8e-11ea-876b-0760fea45d98.png)

**Comment by brandonkelly** [comment]
@davidhellmann there was a bug in 3.4.26 which was fixed in 3.4.27. Sorry about that.

**Comment by davidhellmann** [comment]
@brandonkelly yes, I'm on 3.4.27 and the screens are created with this version :)

**Comment by peimansh** [comment]
I'm still seeing the same behaviour when running 
`utils/repair/project-config`
and then 
`project-config/rebuild`
on 3.4.28.1

**Comment by brandonkelly** [comment]
@davidhellmann @peimansh Can you both please send your `composer.json` and `composer.lock` files, and a database backup, over to support@craftcms.com ?

**Comment by peimansh** [comment]
@brandonkelly Done !

**Comment by ricricucit** [comment]
I can confirm that the same error as @davidhellmann still occurs on craft `3.5.4`

**Comment by ricricucit** [comment]
running `./craft utils/repair/project-config` cleans it up

**Comment by peimansh** [comment]
In my case it is the "Linkit" plugin

**Comment by ricricucit** [comment]
I cannot uninstall plugins, but yes: I keep runnign `utils/repair/project-config`, which helps.

**Comment by peimansh** [comment]
Any fixes being baked ? @brandonkelly 
I'm still experiencing the issue and with every change my project.yaml structure gets back to the old duplicated model and I have to run ./craft utils/repair/project-config to fix it.
it even happens when I rebuild project.yaml

**Comment by brandonkelly** [comment]
@peimansh Please send your Composer files and a database backup into support@craftcms.com, and give us an example of something we can change that will cause the issue.
