### ISSUE TITLE
Lightswitches with 'on' as their default value are stored as NULL on existing entries

### ISSUE THREAD

**Issue by Tam** [craftcms/cms#5679]
### Description
If you create a lightswitch with a default state of 'on' and add it to existing entries, the value will be stored as `NULL` in the database. If you manually re-save the entries, the value will be stored correctly in revisions, but remains `NULL` in the current revision. New entries will store the value correctly.

Current work-around is to check if the lightswitch is `true` or `:empty:`.

### Steps to reproduce

1. Create some entries
2. Create a lightswitch that defaults to 'on' and add it to those entries
3. Try to filter by that lightswitch to show only true.

### Additional info

- Craft version: Craft Solo 3.4.5
- PHP version: 7.3.5
- Database driver & version: MySQL 5.5.5

Plugins | Versions
-- | --
DigitalOcean Spaces Volume | 1.1.2
SEO | 3.6.3
Super Table | 2.4.4
Thumbro | 1.0.0
Typed link field | 1.0.20

**Comment by jamiewade** [comment]
I came across a similar issue: https://github.com/craftcms/cms/issues/3379.

Slightly different as it deals with a number field, but it's the same concept of adding a new field with a default value to an element and not getting the results back you expected.

**Comment by brandonkelly** [comment]
I believe this is the same underlying issue as #5632, which was fixed in 3.4.6. Can you please try updating and see if that fixes it?

**Comment by Tam** [comment]
Doesn't seemed to have done anything, the issue is still there in 3.4.6.1 even after manually resaving the entries.

**Comment by brandonkelly** [comment]
Doh, sorry, I misread your question. Yes, this is expected behavior for now, and I’d say this is in fact a duplicate of #3379.

**Comment by Tam** [comment]
#3379 doesn't seem to account for the fact that saving an existing entry where the lightswitch is set to the default value doesn't save that value, rather storing it as `NULL`. Surely saving the entry should save the value?

**Comment by brandonkelly** [comment]
@Tam that is the part that should have been fixed in 3.4.6. Are you sure it’s still an issue?
