### ISSUE TITLE
Issue adding a child to a disabled parent in structure

### ISSUE THREAD

**Issue by olivierbon** [craftcms/cms#6204]
### Description

From Entries index for a structure section, check a disabled entry and select *Create a new child entry* from the action dropdown. 

Populate the entry and create.

This new entry will show under **All entries** but not in its own structure and if you try to edit it, you'll get an `Entry not found` error.

It looks like the entry gets created fine but no record is created in the `structureelements` table for it.

### Additional info

- Craft version: 3.4.23

**Comment by johandouma** [comment]
Or alternatively, add a new entry, and select a disabled parent. Same result.

**Comment by brandonkelly** [comment]
This has been fixed for the next release.

I’ve also added new `utils/repair/section-structure` and `utils/repair/category-group-structure` commands, which can be used to repair existing structure data, such as adding missing entries back into the structure.

To get the fix early, change your `craftcms/cms` requirement in composer.json to:

```json
"require": {
  "craftcms/cms": "dev-develop as 3.4.23",
  "...": "..."
}
```

Then run `composer update`.

Once updated, go to your project root in your terminal and run this command:

```sh
./craft utils/repair/section-structure <sectionHandle>
```

**Comment by brandonkelly** [comment]
Craft 3.4.24 is out now with this fix + new CLI commands.

**Comment by mark-chief** [comment]
Hello, I think this is still happening.

I am running Craft 3.4.24.

I have an entry that appears under All Entries, but does not appear in its Structure. 
(I am unable to delete the entry because you cannot delete from the All Entries view)

Craft throws a 404 if I try and edit the entry, but the front end URL works.

Can send further logs if you let me know what you need.

**Comment by brandonkelly** [comment]
@mark-chief You will need to run the following command to repair any existing entries that were affected:

```sh
./craft utils/repair/section-structure <sectionHandle>
```
