### ISSUE TITLE
Plugin settings / field settings array getting corrupted and double-packed

### ISSUE THREAD

**Issue by Tam** [craftcms/cms#6317]
### Description
I think this is related to #5533. On a new site I started yesterday the tag settings for the SEO field were being corrupted. There are two issues here that I can see. The first is the value of `template` is being overwritten with the value of `locked`, and the second is that the stored array is double-packed. The SEO plugin isn't doing anything to these values before they are stored which I why I believe it's a Craft issue.

```
settings[title][0][key]: "1"
settings[title][0][locked]: "0"
settings[title][0][template]: "{title}"
settings[title][1][key]: "2"
settings[title][1][locked]: "1"
settings[title][1][template]: "-+{siteName}"
```

Which is then stored as the following:

```
plugins.seo.settings.title.0.__assoc__.0.0: "key"
plugins.seo.settings.title.0.__assoc__.0.1: "1"
plugins.seo.settings.title.0.__assoc__.1.0: "locked"
plugins.seo.settings.title.0.__assoc__.1.1: "0"
plugins.seo.settings.title.0.__assoc__.2.0: "template"
plugins.seo.settings.title.0.__assoc__.2.1: "0" -- should be `{title}`
plugins.seo.settings.title.1.__assoc__.0.0: "key"
plugins.seo.settings.title.1.__assoc__.0.1: "2"
plugins.seo.settings.title.1.__assoc__.1.0: "locked"
plugins.seo.settings.title.1.__assoc__.1.1: "1"
plugins.seo.settings.title.1.__assoc__.2.0: "template"
plugins.seo.settings.title.1.__assoc__.2.1: "1" -- should be `- {siteName}`
```

Running the repair util finds the issues, but obviously the data has already been corrupted:

```
$ php ./craft utils/repair/project-config
Repairing project config ...
- double-packed array found at plugins.seo.settings.title.0
- double-packed array found at plugins.seo.settings.title.1
```

Re-saving the settings causes the array to be corrupted and double-packed again.

### Steps to reproduce

1. Save an SEO field or the SEO settings

### Additional info

- Craft version: 3.4.26
- PHP version: 7.3.5
- Database driver & version: MySQL 5.5.5
- Plugins & versions: SEO 3.6.6

**Comment by Tam** [comment]
Also, if I go into the database and change the values in the `projectconfig` table to be correct and then run `utils/repair/project-config`, the values are corrupted again (but the double-packing is fixed).

**Comment by brandonkelly** [comment]
Thanks for reporting that. Just released 3.4.27 with a fix.

**Comment by mildlygeeky** [comment]
Still seeing issues on 3.4.27 — changes to fields (this specific one is a dropdown field inside a matrix field) keep bringing back disassociative arrays. I can re-run the repair utility, but even then if I alternate between rebuilding and re-syncing the project config, the associative arrays keep coming back, with only the repair utility able to remove them.

Pinging @khalwat on this too, as I believe he's also been encountering project config issues on associative arrays.

**Comment by khalwat** [comment]
Well, someone reported an issue here: https://github.com/nystudio107/craft-imageoptimize/issues/217

...which I believe is a Craft/Project Config issue, not an ImageOptimize issue.

**Comment by mildlygeeky** [comment]
Right — here is what my diff's are looking like after saving a field on 3.4.27 (an Image Optimize field in this case) — I didn't even change anything in this section of the diff (the actual change happened elsewhere), and reviewing merges around project config is becoming increasingly difficult:

<img width="692" alt="Screen Shot 2020-07-14 at 11 10 43 PM" src="https://user-images.githubusercontent.com/273266/87499125-6c3a3680-c627-11ea-9086-9676d6560e7e.png">

**Comment by brandonkelly** [comment]
@mildlygeeky There’s nothing wrong with that as far as I can tell. It’s more verbose but should resolve to the same thing.

@khalwat Guessing https://github.com/nystudio107/craft-imageoptimize/issues/217 was the same as this original issue, which was fixed in 3.4.27. They probably got into that state with the duplicated `'82'` value on Craft 3.4.26, where the bug existed.
