### ISSUE TITLE
[3.5.0-RC4]Edit field settings: preg_replace(): Compilation failed: regular expression is too large at offset 63355

### ISSUE THREAD

**Issue by wsydney76** [craftcms/cms#6474]
### Description

When calling the field edit sites of one (not all) of our matrix fields there is an error:

```
2020-07-28 17:19:59 [-][15][1oavc0q99mclj8p8o279r3kg3v][error][yii\base\ErrorException:2] yii\base\ErrorException: preg_replace(): Compilation failed: regular expression is too large at offset 63355 in E:\craft\temp1\vendor\craftcms\cms\src\helpers\Html.php:603
Stack trace:
#0 E:\craft\temp1\vendor\craftcms\cms\src\web\ErrorHandler.php(75): yii\base\ErrorHandler->handleError(2, 'preg_replace():...', 'E:\\craft\\temp1\\...', 603)
#1 [internal function]: craft\web\ErrorHandler->handleError(2, 'preg_replace():...', 'E:\\craft\\temp1\\...', 603, Array)
#2 E:\craft\temp1\vendor\craftcms\cms\src\helpers\Html.php(603): preg_replace('/(?<=\\s)((?:for...', '$1types-craft-f...', '    \n\n<div id="...')
#3 E:\craft\temp1\vendor\craftcms\cms\src\helpers\Html.php(503): craft\helpers\Html::_namespaceAttributes('<span class="st...', 'types-craft-fie...', false)
#4 E:\craft\temp1\storage\runtime\compiled_templates\fa\fa118250bcc85aad6efc32c8548cd8ae3e2a175ae232ae6ac99d1efdeba16702.php(54): craft\helpers\Html::namespaceHtml('<span class="st...', 'types[craft\\fie...', false)
#5 E:\craft\temp1\vendor\twig\twig\src\Template.php(407): __TwigTemplate_11adebc444070833e1ba68c9efac682ca9321734431ba4730d68278e0a55c8ef->doDisplay(Array, Array)
#6 E:\craft\temp1\vendor\twig\twig\src\Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#7 E:\craft\temp1\storage\runtime\compiled_templates\d3\d3320327abb6661edb2b92db4015235be654a545ea02294e884ae7a7ea724805.php(255): Twig\Template->display(Array)
#8 E:\craft\temp1\vendor\twig\twig\src\Template.php(184): __TwigTemplate_65d9a518817ccf9a7029de686c94f36b0b5196581df0f65f92761803fd816550->block_content(Array, Array)
#9 E:\craft\temp1\storage\runtime\compiled_templates\e9\e98a4f59bf186686812073ba6d5e59c322c25768d51b138be06daf0eef0a4bfb.php(451): Twig\Template->displayBlock('content', Array, Array)
#10 E:\craft\temp1\vendor\twig\twig\src\Template.php(184): __TwigTemplate_d93aad641c3f8c92114cba29a7d8233d7e955968af8a0b0df9c73cc9d10e6493->block_main(Array, Array)
#11 E:\craft\temp1\storage\runtime\compiled_templates\e9\e98a4f59bf186686812073ba6d5e59c322c25768d51b138be06daf0eef0a4bfb.php(306): Twig\Template->displayBlock('main', Array, Array)
#12 E:\craft\temp1\vendor\twig\twig\src\Template.php(184): __TwigTemplate_d93aad641c3f8c92114cba29a7d8233d7e955968af8a0b0df9c73cc9d10e6493->block_body(Array, Array)
#13 E:\craft\temp1\storage\runtime\compiled_templates\e8\e8a4e685366a17cf407746a1a1bfd8feaacc021a49ecddb1752e2573fc40ef2e.php(85): Twig\Template->displayBlock('body', Array, Array)
#14 E:\craft\temp1\vendor\twig\twig\src\Template.php(407): __TwigTemplate_82bc241b7768c45c76ec9f729675d81e044c9dc00b628312368f6e4d28cb27b8->doDisplay('[<span class="s...', Array)
#15 E:\craft\temp1\vendor\twig\twig\src\Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#16 E:\craft\temp1\storage\runtime\compiled_templates\77\775934e6d722bdef7e2dfb08a3a209b05d2030ee3fcc9e23abe89f3f81239ad8.php(57): Twig\Template->display(Array, Array)
#17 E:\craft\temp1\vendor\twig\twig\src\Template.php(407): __TwigTemplate_862fb9e3cabcec1ee73ae284472db7af895a139b86e0f8a0a62a7622508c45e6->doDisplay(Array, Array)
#18 E:\craft\temp1\vendor\twig\twig\src\Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#19 E:\craft\temp1\storage\runtime\compiled_templates\e9\e98a4f59bf186686812073ba6d5e59c322c25768d51b138be06daf0eef0a4bfb.php(154): Twig\Template->display(Array, Array)
#20 E:\craft\temp1\vendor\twig\twig\src\Template.php(407): __TwigTemplate_d93aad641c3f8c92114cba29a7d8233d7e955968af8a0b0df9c73cc9d10e6493->doDisplay(Array, Array)
#21 E:\craft\temp1\vendor\twig\twig\src\Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#22 E:\craft\temp1\storage\runtime\compiled_templates\d3\d3320327abb6661edb2b92db4015235be654a545ea02294e884ae7a7ea724805.php(111): Twig\Template->display(Array, Array)
#23 E:\craft\temp1\vendor\twig\twig\src\Template.php(407): __TwigTemplate_65d9a518817ccf9a7029de686c94f36b0b5196581df0f65f92761803fd816550->doDisplay(Array, Array)
#24 E:\craft\temp1\vendor\twig\twig\src\Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#25 E:\craft\temp1\vendor\twig\twig\src\Template.php(392): Twig\Template->display(Array)
#26 E:\craft\temp1\vendor\twig\twig\src\TemplateWrapper.php(45): Twig\Template->render(Array, Array)
#27 E:\craft\temp1\vendor\twig\twig\src\Environment.php(318): Twig\TemplateWrapper->render(Array)
#28 E:\craft\temp1\vendor\craftcms\cms\src\web\View.php(391): Twig\Environment->render('settings/fields...', Array)
#29 E:\craft\temp1\vendor\craftcms\cms\src\web\View.php(452): craft\web\View->renderTemplate('settings/fields...', '[<span class="s...')
#30 E:\craft\temp1\vendor\craftcms\cms\src\web\Controller.php(243): craft\web\View->renderPageTemplate('settings/fields...', '[<span class="s...', '<span class="st...')
#31 E:\craft\temp1\vendor\craftcms\cms\src\controllers\FieldsController.php(253): craft\web\Controller->renderTemplate('settings/fields...', Array)
#32 [internal function]: craft\controllers\FieldsController->actionEditField(6, Object(craft\fields\Matrix), '2')
#33 E:\craft\temp1\vendor\yiisoft\yii2\base\InlineAction.php(57): call_user_func_array(Array, Array)
#34 E:\craft\temp1\vendor\yiisoft\yii2\base\Controller.php(180): yii\base\InlineAction->runWithParams(Array)
#35 E:\craft\temp1\vendor\craftcms\cms\src\web\Controller.php(181): yii\base\Controller->runAction('edit-field', Array)
#36 E:\craft\temp1\vendor\yiisoft\yii2\base\Module.php(528): craft\web\Controller->runAction('edit-field', Array)
#37 E:\craft\temp1\vendor\craftcms\cms\src\web\Application.php(295): yii\base\Module->runAction('fields/edit-fie...', Array)
#38 E:\craft\temp1\vendor\yiisoft\yii2\web\Application.php(103): craft\web\Application->runAction('fields/edit-fie...', Array)
#39 E:\craft\temp1\vendor\craftcms\cms\src\web\Application.php(280): yii\web\Application->handleRequest(Object(craft\web\Request))
#40 E:\craft\temp1\vendor\yiisoft\yii2\base\Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#41 E:\craft\temp1\web\index.php(19): yii\base\Application->run()
#42 {main}
2020-07-28 17:19:58 [-][15][1oavc0q99mclj8p8o279r3kg3v][info][application] $_GET = [
    'p' => 'admin/settings/fields/edit/6'
]
```

Dumping the used variables: `\Craft::dd([$idPattern,$namespace,$html]);`

```
[
    0 => 'GraphQL_Logo'
    1 => 'yqkiyatfiy'
    2 => '
<svg xmlns=\"http://www.w3.org/2000/svg\" xmlns:xlink=\"http://www.w3.org/1999/xlink\" version=\"1.1\" id=\"yqkiyatfiy-GraphQL_Logo\" x=\"0px\" y=\"0px\" viewBox=\"0 0 400 400\" xml:space=\"preserve\">
<g>
    <g>
        <g>
            
                <rect x=\"122\" y=\"-0.4\" transform=\"matrix(-0.866 -0.5 0.5 -0.866 163.3196 363.3136)\" fill=\"#000000\" width=\"16.6\" height=\"320.3\"></rect>
        </g>
    </g>
    <g>
        <g>
            <rect x=\"39.8\" y=\"272.2\" fill=\"#000000\" width=\"320.3\" height=\"16.6\"></rect>
        </g>
    </g>
    <g>
        <g>
            
                <rect x=\"37.9\" y=\"312.2\" transform=\"matrix(-0.866 -0.5 0.5 -0.866 83.0693 663.3409)\" fill=\"#000000\" width=\"185\" height=\"16.6\"></rect>
        </g>
    </g>
    <g>
        <g>
            
                <rect x=\"177.1\" y=\"71.1\" transform=\"matrix(-0.866 -0.5 0.5 -0.866 463.3409 283.0693)\" fill=\"#000000\" width=\"185\" height=\"16.6\"></rect>
        </g>
    </g>
    <g>
        <g>
            
                <rect x=\"122.1\" y=\"-13\" transform=\"matrix(-0.5 -0.866 0.866 -0.5 126.7903 232.1221)\" fill=\"#000000\" width=\"16.6\" height=\"185\"></rect>
        </g>
    </g>
    <g>
        <g>
            
                <rect x=\"109.6\" y=\"151.6\" transform=\"matrix(-0.5 -0.866 0.866 -0.5 266.0828 473.3766)\" fill=\"#000000\" width=\"320.3\" height=\"16.6\"></rect>
        </g>
    </g>
    <g>
        <g>
            <rect x=\"52.5\" y=\"107.5\" fill=\"#000000\" width=\"16.6\" height=\"185\"></rect>
        </g>
    </g>
    <g>
        <g>
            <rect x=\"330.9\" y=\"107.5\" fill=\"#000000\" width=\"16.6\" height=\"185\"></rect>
        </g>
    </g>
    <g>
        <g>
            
                <rect x=\"262.4\" y=\"240.1\" transform=\"matrix(-0.5 -0.866 0.866 -0.5 126.7953 714.2875)\" fill=\"#000000\" width=\"14.5\" height=\"160.9\"></rect>
        </g>
    </g>
    <path fill=\"#000000\" d=\"M369.5,297.9c-9.6,16.7-31,22.4-47.7,12.8c-16.7-9.6-22.4-31-12.8-47.7c9.6-16.7,31-22.4,47.7-12.8   C373.5,259.9,379.2,281.2,369.5,297.9\"></path>
    <path fill=\"#000000\" d=\"M90.9,137c-9.6,16.7-31,22.4-47.7,12.8c-16.7-9.6-22.4-31-12.8-47.7c9.6-16.7,31-22.4,47.7-12.8   C94.8,99,100.5,120.3,90.9,137\"></path>
    <path fill=\"#000000\" d=\"M30.5,297.9c-9.6-16.7-3.9-38,12.8-47.7c16.7-9.6,38-3.9,47.7,12.8c9.6,16.7,3.9,38-12.8,47.7   C61.4,320.3,40.1,314.6,30.5,297.9\"></path>
    <path fill=\"#000000\" d=\"M309.1,137c-9.6-16.7-3.9-38,12.8-47.7c16.7-9.6,38-3.9,47.7,12.8c9.6,16.7,3.9,38-12.8,47.7   C340.1,159.4,318.7,153.7,309.1,137\"></path>
    <path fill=\"#000000\" d=\"M200,395.8c-19.3,0-34.9-15.6-34.9-34.9c0-19.3,15.6-34.9,34.9-34.9c19.3,0,34.9,15.6,34.9,34.9   C234.9,380.1,219.3,395.8,200,395.8\"></path>
    <path fill=\"#000000\" d=\"M200,74c-19.3,0-34.9-15.6-34.9-34.9c0-19.3,15.6-34.9,34.9-34.9c19.3,0,34.9,15.6,34.9,34.9   C234.9,58.4,219.3,74,200,74\"></path>
</g>
</svg>
'
]
```

### Steps to reproduce

1.
2.

### Additional info

- Craft version: 3.5.0-RC4
- PHP version: 7.4.7
- Database driver & version:
- Plugins & versions:

**Comment by brandonkelly** [comment]
I’m not able to reproduce this, but I think I see how it could happen, and probably just fixed it.

Can you test for me? Change your `craftcms/cms` requirement to `3.5.x-dev`, and then run `composer update`.

**Comment by wsydney76** [comment]
@brandonkelly Thanks, the page appears now without error.

**Comment by brandonkelly** [comment]
Awesome, thanks for testing!

**Comment by chanwhab** [comment]
I can also confirm that this issue is resolved.

**Comment by circa1977** [comment]
I just ran `3.5.0-RC2 => 3.5.0-RC4` and am getting this when trying to edit one of my Matrix fields. Changing my required version to `3.5.x-dev` and running `craft update all` says `You’re all up-to-date!`.

**Comment by circa1977** [comment]
@brandonkelly Following up to clarify my previous comment, this is not resolved for me and I'm up to date as prescribed.

**Comment by brandonkelly** [comment]
@circa1977 After editing `composer.json` you need to run `composer update`, not `craft update all`.

**Comment by circa1977** [comment]
There we go. Thanks, @brandonkelly!

**Comment by brandonkelly** [comment]
Craft 3.5 RC5 is out now with that fix.
