### ISSUE TITLE
[3.5.0-RC5] Title field displays as "translatable" even if it isn't

### ISSUE THREAD

**Issue by mmikkel** [craftcms/cms#6503]
### Description

The Title field always displays as translatable (i.e. with the little speech bubble icon and the "Translatable" tooltip on hover), even if it's set to not being translatable in the entry type's field layout.

Note that the title is not actually translatable, it's just presented as such in the entry edit form.

### Steps to reproduce

1. Select "Not translatable" in the "Title Translation Method" dropdown in an entry type's settings page
2. Confirm that the title field still has the speech bubble icon in the entry edit form

### Additional info

- Craft version: 3.5.0-RC5
- PHP version:
- Database driver & version:
- Plugins & versions:

**Comment by brandonkelly** [comment]
Whoops, must have forgotten to hook that up. Fixed now for the next release.

**Comment by brandonkelly** [comment]
Craft 3.5 RC6 is out now with this fix.

**Comment by hassanmah** [comment]
@brandonkelly I still get this on Craft CMS 3.5.11.1

![image](https://user-images.githubusercontent.com/3025707/94028886-2e3e5900-fdb4-11ea-8b7e-d813fc7fe244.png)

**Comment by brandonkelly** [comment]
@hassanmah In your entry type’s settings, what is the Title Translation Method set to?

**Comment by hassanmah** [comment]
@brandonkelly I don't have an option for Title Translation Method, it's not a multisite.

**Comment by brandonkelly** [comment]
Ahh, ok, just fixed that for the next release.

**Comment by brandonkelly** [comment]
Craft 3.5.12 is out now with that fix.
