### ISSUE TITLE
Graphql asset alias eager loading returns empty array

### ISSUE THREAD

**Issue by smcyr** [craftcms/cms#6874]
### Description
I have this query:
```
query FetchPage($uri: [String]) {
  pageEntry: entry(site: "*", uri: $uri) {
    ...PageFragment
  }
}

fragment PageFragment on EntryInterface {
  id
  ... on blogPost_blogPost_Entry {
    ...BlogPostFragment
  }
  ... on jobsList_jobsList_Entry {
    ...JobsListFragment
  }
}

fragment ImageFragment on AssetInterface {
  id
  url
}

fragment BlogPostFragment on blogPost_blogPost_Entry {
  image: blogBannerImage {
    ...ImageFragment
  }
}

fragment JobsListFragment on jobsList_jobsList_Entry {
  image: careerBannerImage {
    ...ImageFragment
  }
}

# Query variables:
{
  "uri": "en/careers/jobs"
}
```
If I execute it, it returns an empty array for `image`:
```
{
  "data": {
    "pageEntry": {
      "id": "49474",
      "image": []
    }
  }
}
```
But if I remove the BlogPostFragment or the image alias, it returns the array normally.

### Additional info

- Craft version: 3.5.11.1
- PHP version: 7.3.18
- Database driver & version: PostgreSQL 12.4

**Comment by smcyr** [comment]
I had the same error with a matrix block which had also two different names but the same alias `section`.

**Comment by andris-sevcenko** [comment]
Thanks for reporting! This has been fixed for the next Craft release!

**Comment by brandonkelly** [comment]
Craft 3.5.12 is out now with that fix.

**Comment by cyponthemic** [comment]
I am still experiencing the issue. 

![image](https://user-images.githubusercontent.com/7971753/95391414-bee37000-0942-11eb-849c-d4b2ac833651.png)

on Craft 3.5.12.1

**Comment by cyponthemic** [comment]
Further info: just noticed it only happens on Super Table's blocks

**Comment by andris-sevcenko** [comment]
Yeah, I can reproduce this.

**Comment by andris-sevcenko** [comment]
@cyponthemic Thanks for reporting! Just fixed this for the next release!

**Comment by brandonkelly** [comment]
Craft 3.5.13 is out now with that fix.
