### ISSUE TITLE
Clicking on Publish Draft should redirect users to the entries list, just like Save

### ISSUE THREAD

**Issue by jsunsawyer** [craftcms/cms#7614]
Currently, when a user saves an entry (not save and continue editing), they are taken back to the entries list.

With the updated way that new entries are created, the only way to immediately publish a new entry is to click on `Publish Draft`. Doing so keeps you in that entry's view, and is inconsistent with prior behavior where a user could simply click `Save`, then return to the entries list.

**Comment by brandonkelly** [comment]
The convention is that “Save”-esque buttons will take you up a level from wherever you are. If you’re currently viewing an entry draft, going back a level would mean going to its Current revision.

Open to reconsidering that, but it feels like it’s working as expected to me already.

**Comment by zzseba78** [comment]
Agree with @jsunsawyer , Craft removed the minimun interaction needed to quickly publish a new entry, one click.

I don´t like the concept of every entry is a new draft, i think draft should be a second action as it were before, but aside from that, be able to simply create a entry and primary action "Publish Draft" on red, and back to listing. Simple and quick.

**Comment by brandonkelly** [comment]
@zzseba78 That’s a separate discussion, which is already happening over at #6681. We’re revisiting the workflow for 3.7.

**Comment by jsunsawyer** [comment]
@brandonkelly Here's the scenario where I think this would be helpful.

Currently, we set up our categories as entries (we moved away from using actual categories a while back due to some sort order limitations, and potential future changes to how entries work in Craft).

So, our users may be adding multiple categories, one after another, with each only requiring a title.

Here's what they currently have as options to publish.
![Screen Shot 2021-02-26 at 9 01 08 AM](https://user-images.githubusercontent.com/1007191/109331374-9e448580-7811-11eb-8e84-22ef550efa4b.png)

Most users aren't going to use the dropdown, and instead use the `Publish draft` button. This keeps them in the entry, so it requires another step to add their next entry. While they could use the `Publish and add another` option, this is often overlooked. I consider things in this dropdown more power-user features.

Regardless of the `Publish and add another` option, there is something to be said about seeing the list of categories after adding a new one. This helps provide the user with some context as to what has already been added. Imagine creating content for an unordered list where you can't reference the other list items.

Anyway, not a huge deal if this isn't changed, but figured it'd make the new experience feel a bit closer to pre-draft update Craft.

**Comment by brandonkelly** [comment]
This is resolved for Craft 3.7 (see #7899).

The buttons are unchanged for deliberately-created drafts, and in that case “Publish draft” continues to take you back to the entry edit page, which still feels right in that case. However when you create a _new_ entry, it‘s no longer obvious that you are actually editing an unpublished draft; it feels more like you’re already editing the actual entry and therefore there’s only one Save button, and it behaves like a normal entry Save button – publishing the entry and redirecting to the Entries index page.

**Comment by jsunsawyer** [comment]
@brandonkelly I looked over the 3.7 changes in the issue you linked, but don't completely understand how the provisional draft stuff works without trying it out.

If "Publish Draft" does still exist at some point in the flow, would it not still make sense for this to behave as the standard "Save" logic that has existed in the past – returning users to the entries index page? Curious what makes it "feel right" to keep the user on the entry they just published. Is there an expectation that they make further edits after publishing content? I might just not be following what the intent of "Publish Draft" is.

**Comment by mmikkel** [comment]
@jsunsawyer In 3.7, the "Publish draft" button only appears for deliberately saved/created drafts – just like it was prior to 3.6. And IIRC, publishing a draft has always redirected the author back to the entry's current revision.

New entries/provisional drafts (aka auto-drafts or "unsaved changes") in 3.7 work more like a "state" for the current revision, and less like real drafts like in 3.6. As such, they only have the primary "Save" button (in addition to a secondary "Save as draft" button). The Save button will update the current revision and redirect the author back to the entries index – again, just like updating the current revision has always worked.

**Comment by jsunsawyer** [comment]
@mmikkel Hmm, I'll probably just need to play around with it. Still not really following the flow of things.

And yeah, publishing draft may have always redirected back to the entry's current revision (as of 3.6 when it was added I think), but that's what this initial issue was about. And it seems that has not changed, even though there have been other improvements made in general.

**Comment by mmikkel** [comment]
No, the Publish Draft button (and the way it works) has been a thing since way before 3.6. What changed in 3.6 was that it became the primary action for new entries. 3.7 reverts that. The original issue specifically mentions this behavior in relation to creating new entries, but FWIW that won’t be the case going forward.

**Comment by jsunsawyer** [comment]
@mmikkel You're right that I specifically mentioned that behavior in relation to creating new entries, but it was only an example to prove my point as to why it should work that way I expect.

With the changed behavior (again, I may not fully understand it, which is why I asked for some clarity), I still think it makes little sense to keep the user in an edit view once they have published their draft (assuming "Publish Draft" takes an entry from a draft state to a live, published entry – and doesn't simply convert a provisional draft to an unpublished draft, which would be confusing).

**Comment by brandonkelly** [comment]
> I still think it makes little sense to keep the user in an edit view once they have published their draft (assuming "Publish Draft" takes an entry from a draft state to a live, published entry – and doesn't simply convert a provisional draft to an unpublished draft, which would be confusing).

@jsunsawyer I disagree; as I said I think returning to the Current revision feels right in the case of publishing an intentionally-created draft. I think of the IA as follows (based on a typical navigation flow to get to a draft’s edit page):

- Entries index page
  - Entry edit page (Current revision)
    - Draft edit page

Primary form actions always take you one level up, by convention. So with this IA, the correct place to redirect after publishing a draft would be the Current revision.

**Comment by jsunsawyer** [comment]
Ahhh, I got it now. Thanks for the explanation @brandonkelly.

For some reason, I was specifically thinking about this being used in auto-saved/unpublished drafts, and not actual drafts for updates to existing entries.

The way you have it set up makes sense. Sorry for the confusing back and forth @mmikkel !
