### ISSUE TITLE
Draft merge issue on multiple groups

### ISSUE THREAD

**Issue by jing-liu-anne** [craftcms/cms#9729]
### Description

I have a site with multiple groups with different language. All entries are enabled across sites. Editors come from different regions, they are only responsible for editing the language of their region. 

Create a draft on site A, edit the entry on another group site and publish the change. Switch to site A draft version, an extra field will appear. After publishing the draft, change of other group site disappeared. I think changes to matrix blocks made in the draft are not merged correctly into the current.

### Steps to reproduce

1. Starts edits from current version and save as a draft on site US (User A).
2. Starts edits on site NL from current version and publishes them (User B). 
3. Switch to site US, there is one more field in the draft. Publishes the draft on site US (User A).
4. The last change on site NL disappeared (User B).

A unknowingly overwriting B's work. Hope that the site of each group will not affect each other, or the draft of site NL can automatically merge the latest changes. Also do not repeat the field.

Section’s Propagation Method is : Save entries to all sites enabled for the section
Matrix field’s Propagation Method: Save blocks to all sites the owner element is saved in 

Here's a recording showing the issue:

https://user-images.githubusercontent.com/88373506/129690928-91090e84-abc2-448d-96df-33886e9f953d.mp4

### Additional info

- Craft version: Craft Pro 3.7.8
- PHP version:  7.4.15
- Database driver & version: MySQL 8.0.24
- Plugins & versions:

**Comment by jing-liu-anne** [comment]
If you need a database backup, Dande Sun has emailed you a few days ago. (for the issue: https://github.com/craftcms/cms/issues/9664) 

Thanks in advance!

**Comment by brandonkelly** [comment]
Thanks for reporting that! I was indeed able to reproduce with that DB backup Dande sent in.

We just released Craft 3.7.9 with a fix.

**Comment by jing-liu-anne** [comment]
Thanks for fixing the draft merge issue. I have upgrading to Craft Pro 3.7.9. I find field is still appear twice when switch to draft version. Please see the recording above (1 minute 13 seconds). Please help fix.

**Comment by jing-liu-anne** [comment]
I find another issue. When create new entry, if you click the button "Create Entry" before auto-saving,  all fields will appear twice (Not every time, sometimes). If you create entry after auto-saving. It will not happen.

**Comment by brandonkelly** [comment]
@jing-liu-anne I’m not able to reproduce either of those. Can you please see if you can come up with specific steps to reproduce them (on 3.7.9+ where the value merging bug has been fixed), and post as a new issue?
